### ISSUE TITLE
Remove files that overlap with skl2onnx

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#1]
Since we are re-using part of skl2onnx code, let's see how many changes we did, and in case remove all files where we overlap and add include.

**Comment by ksaur** [comment]
I tried to use `skl2onnx==1.6.0` but this gave many segfaults; but it seems we can use`skl2onnx==1.5.0` for now.

It is difficult to port directly based on all of the changes shown [here](https://cisl.visualstudio.com/Hummingbird/_git/Hummingbird/commit/a7ac39811c27a625507befda3d0a149eb7fa7f05) with many added/modified functions in _topology.py and parse.py

**Comment by interesaaat** [comment]
All modifications appear to be on scoping. This is because in PyTorch all variable names need to be unique, while in ONNX probably you can scope them. Maybe we can achieve the same result by using a single scope? Just putting an idea.
