### ISSUE TITLE
Tree classifiers return wrong labels while probabilities match

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#10]
Apparently `torch.argmax` returns the last matching value, while `np.argmax` return the first one. This is general is not a problem, except when we get the same probabilities for 2 or more classes. 

This will hopefully get fixed once [this ](https://github.com/pytorch/pytorch/issues/10370) will get closed.

Once this is fixed we should add assertion over the labels results as well. At this point this assertions won't be useful since they will likely often fails.

**Comment by ksaur** [comment]
Adding this branch to show the bug 
https://github.com/microsoft/hummingbird/tree/kasaur/predict_proba_problem

**Comment by interesaaat** [comment]
Ok this should be fixed in pytorch 1.7 ([issue](https://github.com/pytorch/pytorch/pull/42004)).
