### ISSUE TITLE
Minor documentation improvements

### ISSUE THREAD

**Issue by KranthiGV** [microsoft/hummingbird#104]
When generating documentation using pdoc, we observe a few warnings:

```
/home/neumann/miniconda3/envs/bird/lib/python3.7/site-packages/pdoc/html_helpers.py:498: ReferenceWarning: Code reference `hummingbird.supported` in module "hummingbird.ml.convert" does not match any documented object.
  linked = re.sub(r'[a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)*(?:\(\))?', handle_refname, code_span)
/home/neumann/miniconda3/envs/bird/lib/python3.7/site-packages/pdoc/html_helpers.py:498: ReferenceWarning: Code reference `hummingbird.supported_configurations` in module "hummingbird.ml.convert" does not match any documented object.
  linked = re.sub(r'[a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)*(?:\(\))?', handle_refname, code_span)
```

1. We should change `hummingbird.supported` to `hummingbird.ml.supported` for the documentation site to correctly link them.
2. Docstrings mention that `hummingbird.supported_configurations` shows the set of supported extra configurations.
However, `supported_configurations` is not found in the repo (within any submodule). 
Is it not yet released?

**Comment by KranthiGV** [comment]
Regarding 2,
I see that in supported.py, we define them as
```
# Supported configurations settings accepted by Hummingbird are defined below.
N_FEATURES = "n_features"
"""Number of features expected in the input data."""

TREE_IMPLEMENTATION = "tree_implementation"
"""Which tree implementation to use. Values can be: gemm, tree-trav, perf_tree_trav."""
```
It is not (yet) encapsulated as `supported_configurations`.

**Comment by interesaaat** [comment]
This is a bug. We moved `supported configurations` into `supported`. Do you want to file a PR for this?

**Comment by KranthiGV** [comment]
Yes, sure. I'd be happy to take it up.
