### ISSUE TITLE
Automate document generation

### ISSUE THREAD

**Issue by KranthiGV** [microsoft/hummingbird#107]
- We have been manually refreshing documentation (generated using pdoc) till now.
- However, this can be automated using Github actions.

Open questions:
- Do we want to update github pages, too? This may require us to monitor the quality of docstrings closely. This can be a deterrent to a first time contributor.
- What do we do with runtime warnings?
- Is generation of documentation a pre-push or post-push item? If it's post-push, what if we get errors?

**Comment by cyberShaw** [comment]
I am new to open source and would love to work on this issue, can I contribute?

**Comment by interesaaat** [comment]
Welcome @cyberShaw! I assigned this issue to you.

**Comment by ksaur** [comment]
Welcome @cyberShaw! Great questions @KranthiGV, thanks for raising this.

We had originally intended to use Sphinx for documentation, but that setup required a bit more  time than originally planned, so for now we are using pdoc.  (Definitely open to revisiting that decision!)

In terms of order of refreshing content, there's a [nice list](https://sphinxtechnicalwriting.readthedocs.io/en/latest/cd/cdindex.html) on the sphinx page that we could use for our pdoc doc gen flow for now.

`Do we want to update github pages, too?`
My gut reaction is yes; hopefully the docstrings aren't too much of a burden on new contributors. We should definitely write some text about this in CONTRIBUTING.md, as I see that's missing!

`What do we do with runtime warnings...Is generation of documentation a pre-push or post-push item? If it's post-push, what if we get errors?`
I think this is something we might have to experiment with a bit.  I am not familiar with how strict the error tolerance is, I don't want to discourage users.  For example, it's probably ok if the doc is "slightly off-format" vs "totally broken", and I'm not sure where the error threshold falls.

**Comment by interesaaat** [comment]
I did a simple PR (#223) that run pdoc as a pre-commit. In this way, if the code ends up in changing the documentation, the html page with the doc is update automatically. I guess we can go with this solution until we don't have better options. We still need to fix the pipeline for updating the gh-page. That is still manual at the moment.
