### ISSUE TITLE
Change assert(... is not None) into assertIsNotNone

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#113]
There are several instances in the (test) code where we do `assert(... is not None)`, e.g., ([here](https://github.com/microsoft/hummingbird/blob/e7fb7ba5f4c3ba4cbab637ed5926848dfcabf998/tests/test_sklearn_decision_tree_converters.py#L31)). It is better to change it into `assertIsNotNone`.

**Comment by KranthiGV** [comment]
Mind if I take this up?

**Comment by interesaaat** [comment]
Closed by #114.
