### ISSUE TITLE
Add TorchScript backend

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#115]

**Comment by KranthiGV** [comment]
I'm interested to work on this. Is it okay if I research a little and come back with a proposal?

**Comment by interesaaat** [comment]
I think that (beside checks) the edits should be limited to the [container](https://github.com/microsoft/hummingbird/blob/master/hummingbird/ml/_container.py).

**Comment by KranthiGV** [comment]
Started working on this now.

**Comment by ksaur** [comment]
Hi @KranthiGV, just checking in! Have you gotten a chance to work on this?

**Comment by KranthiGV** [comment]
I did make good progress on that but not enough for a PR. I should've been more responsive here.
I really appreciate the patience and that you people took up the task as well.

**Comment by interesaaat** [comment]
Don't worry :) Sorry if we wasted some of your progresses.
