### ISSUE TITLE
Running sklearn example on Colab: module object not callable

### ISSUE THREAD

**Issue by ucalyptus** [microsoft/hummingbird#117]
Check the gist colab nb here https://gist.github.com/ucalyptus/bcf09b711009b87e94f989cb13035909
Did install sklearn 0.21.3 beforehand and enabled GPU.

**Comment by ucalyptus** [comment]
cc: @interesaaat @ksaur

**Comment by bhishanpdl** [comment]
I was going to raise the same issue. 

Date: Jun 10, 2020

```python
torch.__version__   # '1.5.0+cu101'
sklearn.__version__ # '0.21.3'
!pip freeze | grep humming  # hummingbird-ml==0.0.1

```

**Comment by interesaaat** [comment]
This problem is related to this [issue](https://github.com/microsoft/hummingbird/issues/82). I will try to push a new version today.

**Comment by ksaur** [comment]
https://pypi.org/project/hummingbird-ml/0.0.2/

Hopefully this new release will fix that issue.

**Comment by ksaur** [comment]
@ucalyptus  @bhishanpdl Can you please try it out and let me know if this fixes it; or if there is some other problem?  Thanks for the feedback!
```
pip install hummingbird-ml==0.0.2
```

**Comment by ksaur** [comment]
Closing because this is believed to be resolved; please reopen if further issues

**Comment by ucalyptus** [comment]
@ksaur yes 0.0.2 solved it , thanks a lot
