### ISSUE TITLE
Cleanup Normalizer Converter Code

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#126]
We have the original draft of the normalizer code uploaded in [this branch](https://github.com/microsoft/hummingbird/tree/cleanup/normalizer). All credit here goes to @scnakandala, the original author and brains behind this.

It contains an un-edited implementation of SklearnNormalizer [here](https://github.com/microsoft/hummingbird/blob/cleanup/normalizer/hummingbird/ml/operator_converters/normalizer.py).

There is a single test file [here](https://github.com/microsoft/hummingbird/blob/cleanup/normalizer/tests/test_sklearn_normalizer_converter.py) that needs to be cleaned up and passing.

**Comment by ahmedkrmn** [comment]
Hey Karla,
Can I take up this one?

**Comment by ksaur** [comment]
Hi @ahmedkrmn Sure, thank you!

**Comment by ksaur** [comment]
I did one small commit to the branch, just adding a flag that might be confusing and cause the code to not work; let me know if you run into issues or have questions!
