### ISSUE TITLE
Add sklearn.ensemble.HistGradientBoostingRegressor

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#127]
This should be easy since we already have `HistGradientBoostingClassifier` there.

**Comment by TuanNguyen27** [comment]
hi @interesaaat I'm interested in working on this issue !

**Comment by ksaur** [comment]
Hello, welcome @TuanNguyen27! It's all yours; please let us know if you have questions/doubts.

**Comment by ksaur** [comment]
thank you @TuanNguyen27 !
