### ISSUE TITLE
Cleanup and import SKL Feature Pre-processing: OneHotEncoder

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#136]
We have the original draft of the OneHotEncoder code uploaded in this [branch](https://github.com/microsoft/hummingbird/tree/cleanup/one-hot-enc). All credit here goes to @scnakandala, the original author and brains behind this.

It contains an un-edited implementation of OneHotEncoder [here](https://github.com/microsoft/hummingbird/blob/cleanup/one-hot-enc/hummingbird/ml/operator_converters/one_hot_encoder.py).

There is a single test file [here](https://github.com/microsoft/hummingbird/blob/cleanup/one-hot-enc/tests/test_sklearn_one_hot_encoder_converter.py) that needs to be cleaned up and passing.

Notes:
* We had to treat strings a bit differently because of the way they are represented in tensors
  *  We should add more robust tests here
* the `retain_order`  flag in `OneHotEncoder` is not yet implemented. We can wait on that for later unless someone gets inspired.

**Comment by TuanNguyen27** [comment]
hey @ksaur can i also work on this ? :)

**Comment by ksaur** [comment]
I did one small commit to the branch, just adding a flag that might be confusing and cause the code to not work; let me know if you run into issues or have questions!
