### ISSUE TITLE
Cleanup Scalar Converter Code

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#137]
We have the original draft of the scaler code uploaded in [this branch](https://github.com/microsoft/hummingbird/tree/cleanup/scaler). All credit here goes to @scnakandala, the original author and brains behind this.

It contains an un-edited implementation of RobustScaler, MaxAbsScaler, MinMaxScaler, and StandardScaler [here](https://github.com/microsoft/hummingbird/blob/cleanup/scaler/hummingbird/ml/operator_converters/scaler.py).  We need to integrate this old code into the current code.

There is a single test file [here](https://github.com/microsoft/hummingbird/blob/cleanup/scaler/tests/test_sklearn_scaler_converter.py) that needs to be cleaned up, expanded, and passing.

**Comment by ahmedkrmn** [comment]
Hi Karla,
Can I work on this one after #145 is merged?
