### ISSUE TITLE
Add !pip to notebooks?

### ISSUE THREAD

**Issue by jspisak** [microsoft/hummingbird#143]
Hi There,
It would be nice to add `!pip install hummingbird_ml` to the notebooks so when you execute them in colab you dont need to add a line for this manually. I assum though that this is not ideal for CI so please disregard if too much trouble.

**Comment by interesaaat** [comment]
@ksaur WDYT?

**Comment by ksaur** [comment]
I like this idea! We can definitely do this right away for the blog example notebook and the sklearn example notebook and add `!pip install hummingbird-ml`.

The only concern I have is that our new installer for  xgboost and lightGBM (that removes these libraries as dependencies unless specified) would need to be `!pip install hummingbird-ml[extra]` for the xgb and lgbm notebooks. (This "bleeding edge" installer change is not yet in the pypi packages, so we could consider waiting until after we push `0.0.3` next week.) However, any installation with pypi `0.0.2` now will simply install all optional packages (xgboost and lightGBM), and the `[extra]` syntax will just give a warning I believe, so I think that should be fine...but we should test it!

@jspisak are you interested in contributing this/PR? (Note that we don't yet have ci/cd set up for our notebooks... I'll raise an issue on that; thanks for reminding us!) In the meantime just test your changes on your machine and make sure that they run, and we'll run them as well before merging, if this is something you'd like to help out with!

**Comment by jspisak** [comment]
Hey Guys - sure, glad to put up a PR. I'll work on this by EOW.  thanks!
