### ISSUE TITLE
Add SKL Other Classifiers

### ISSUE THREAD

**Issue by scnakandala** [microsoft/hummingbird#153]
Add support for other SKL classifiers (i.e., other than linear models and tree-based models)

This includes:

- MLPClassifier
- BernoulliNB
- GaussianNB
- MultinomialNB

**Comment by scnakandala** [comment]
@interesaaat can you assign this to me.

**Comment by ksaur** [comment]
@scnakandala so good to see you here; let us know if there is anything else of your own work that you'd like to "re-work" on!! :-D
