### ISSUE TITLE
Is it possible to create a sklearn Pipeline with GridSearch?

### ISSUE THREAD

**Issue by EmanuelFontelles** [microsoft/hummingbird#159]

**Comment by ksaur** [comment]
Hi, are you referring to https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html ?

This is not an operator we currently support.

**Comment by ksaur** [comment]
Could you please provide more details?

**Comment by dcshapiro** [comment]
Hi. I had a similar issue. You can unwrap GridSearchCV into a pipeline object.

Here is how to extract the pipeline from the gridsearch @EmanuelFontelles

from sklearn.pipeline import Pipeline
pipeline=Pipeline(steps=skl_model.estimator.steps)
model = convert(pipeline, 'pytorch') # <-- this step still fails for me, but it may work for you if your estimators are supported. I opened a separate ticket about the issue I'm having, which is countvectorizer-related

**Comment by interesaaat** [comment]
Thanks @dcshapiro! Closing the issue for now.
