### ISSUE TITLE
Cleanup SKL LabelEncoder Converter Code

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#160]
We have the original draft of the SKL LabelEncoder code uploaded in [this branch](https://github.com/microsoft/hummingbird/tree/cleanup/label-encoder). All credit here goes to @scnakandala, the original author and brains behind this.

It contains an un-edited implementation of LabelEncoder [here](https://github.com/microsoft/hummingbird/blob/cleanup/label-encoder/hummingbird/ml/operator_converters/skl_label_encoder.py).

There is a test file [here](https://github.com/microsoft/hummingbird/blob/cleanup/label-encoder/tests/test_sklearn_label_encoder_converter.py) that needs to be cleaned up and passing (and also tests added for errors).

**Notes:**

* We had to treat strings a bit differently because of the way they are represented in tensors
  * We should add more expansive tests
* In the numeric label encoder, there is a tricky spot [here](https://github.com/microsoft/hummingbird/blob/cleanup/label-encoder/hummingbird/ml/operator_converters/skl_label_encoder.py#L46) related to running on GPU vs CPU.  
  * There may be some bugfixes/improvements that are available now. Our CI/CD pipeline is not currently GPU-enabled, but it would be helpful to be able to run this on a GPU-enabled machine when developing.

**Comment by amueller** [comment]
Btw, many people that are using ``LabelEncoder`` should actually be using ``OneHotEncoder``. ``LabelEncoder`` was meant for labels i.e. targets, not features, and only supports a single column, while ``OneHotEncoder`` supports multiple columns.

**Comment by interesaaat** [comment]
Good to see you here @amueller! :) Yes we also have `OneHotEncoder`, it is work in progress in PR #147.

**Comment by ksaur** [comment]
closed via #374
