### ISSUE TITLE
train with GPU

### ISSUE THREAD

**Issue by kvnsng** [microsoft/hummingbird#165]
Hi,

Just wondering if the current version supports training models with GPU as well.

**Comment by interesaaat** [comment]
Hi @songkevinc! We have explored the idea of training in a [research paper](https://arxiv.org/abs/1906.03822) but Hummingbird is currently only for inference. The GEMM implementation is really close to what we tried in the paper so in theory it should be not hard to add training.

**Comment by kvnsng** [comment]
Ah, gotcha. Sounds good! Looking forward to the development.
