### ISSUE TITLE
Support for LGBMRanker?

### ISSUE THREAD

**Issue by go2ready** [microsoft/hummingbird#172]
Hello there, 

I am wondering if the current implementation supports convertion from LightGBMRanker which is part of the LightGBM package? Is there anything special to the LightGBMRanker and will the converter for LGBMRegressor works in this case? Here is the error I got when I try to convert the LGBMRanker

```
MissingConverter: Unable to find converter for model type <class 'lightgbm.sklearn.LGBMRanker'>.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter implemented.
Please fill an issue at https://github.com/microsoft/hummingbird.
```

This is the doc to LGBMRanker https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRanker.html

Thanks in advance!

**Comment by ksaur** [comment]
Hi  @go2ready, thanks for filing this! We don't currently have a converter for `LGBMRanker`,  but from a quick glance it looks similar enough that a few modifications to the converter for `LGBMRegressor` might make it work.
We'll look into it and get back to you!

**Comment by ksaur** [comment]
@go2ready thanks for the request, please let us know if you have additional questions!

**Comment by go2ready** [comment]
Thanks @ksaur , when will this be in the next release?

**Comment by ksaur** [comment]
Hi @go2ready - we don't have a specific release schedule as of yet, but generally 1-2 weeks as features are ready. Hopefully you can pull from source in the meantime, and I'll make sure to ping you when the proper release is ready!

**Comment by ksaur** [comment]
@go2ready - This was in today's release :)
