### ISSUE TITLE
Support for XGBRanker

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#174]
[XGBRanker](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRanker) should be a very simple add; similar to #173 

It should hopefully just involve (1) either using or slightly tweaking the converter for XGBRegressor (2) writing tests and making sure they pass

**Comment by KranthiGV** [comment]
I was looking at this a couple of days ago. Is it okay if I pick this up?

**Comment by interesaaat** [comment]
Go for it!

**Comment by ksaur** [comment]
closed with #189
