### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by zhanjiezhu** [microsoft/hummingbird#187]
Hi there, 

When I'm testing Hummingbird with GPU for more and deeper trees (worked fine if I have less trees), I got OOM error: 

"CUDA out of memory. Tried to allocate 5.96 GiB (GPU 0; 11.91 GiB total capacity; 6.47 GiB already allocated; 4.74 GiB free; 6.48 GiB reserved in total by PyTorch)"

I'm using:
CUDA 10.1, Pytorch 1.5.1+cu101
RandomForestRegressor from sklearn
total number of samples: 800k
number of features: 100
number of trees: 1000
average tree depth: 15
average number of nodes per tree: 3700

Is it expected? Any idea how to make it work for more and deeper trees?

Thanks!

**Comment by interesaaat** [comment]
Is this on a [Windows machine](https://github.com/microsoft/hummingbird/issues/176)?

**Comment by zhanjiezhu** [comment]
@interesaaat no, it's on Linux (CentOS Linux 7)

**Comment by zhanjiezhu** [comment]
Here is the code to reproduce OOM, would be great if you could test on your side as well, it's simply coping a tree multiple times so don't need to wait for long training time for large number of trees. In my case, it throws OOM when number of trees are 500, and it seems the GPU memory are not being freed but somehow aggregated: "CUDA out of memory. Tried to allocate 1.49 GiB (GPU 0; 11.91 GiB total capacity; 11.06 GiB already allocated; 89.38 MiB free; 11.13 GiB reserved in total by PyTorch)".
Downgrading pytorch to 1.4.0 doesn't help.

```
from sklearn.ensemble import RandomForestClassifier
from hummingbird.ml import convert
import numpy as np
import time

rs = np.random.RandomState(0)
X = rs.rand(800000, 100)
Y = rs.randint(0, 2, 800000)

# only train 1 tree and later duplicate that tree to avoid long training time
rfc = RandomForestClassifier(n_estimators=1, max_depth=15, n_jobs=-1, random_state=0)
rfc.fit(X, Y)

for num_tree in [100, 500, 1000, 2000, 5000]:
    rfc.estimators_ = [rfc.estimators_[0] for i in range(num_tree)]
    rfc.n_estimators = len(rfc.estimators_)
    print(f'number of trees: {len(rfc.estimators_)}')
    start = time.time()
    model = convert(rfc, 'pytorch')
    print(f'time for conversion: {time.time() - start}')
    model.to('cuda')
    start = time.time()
    model.predict(X)
    print(f'time for prediction with gpu: {time.time() - start}')

```

**Comment by interesaaat** [comment]
Ok thanks! I will take a look.

**Comment by interesaaat** [comment]
Sorry for the late turnaround. We did some experiment and yes, we consume more memory than optimal (we reported some number in the paper too, I think we are about 2X from Sklearn). It would be good to understand whether we can improve this or not. The memory layout we are using I think it's close to the Sklearn one, so the problem may actually be the tensor operations. 

On the other hand, I still have to understand if the memory is not freed correctly for some reason.

**Comment by zhanjiezhu** [comment]
@interesaaat thanks! I will also try to look at this again and do some memory profiling in a few days

**Comment by zhanjiezhu** [comment]
indeed in this example for 800k rows * 100 columns is already quite a large array. Simply batching the X works, but would be great if there could be some automatic batching being done in Hummingbird, I saw that in the paper it's using batch size 10k rows, is it a good number to use?

**Comment by ksaur** [comment]
Hi @zhanjiezhu ! Yes, a batch size of at least 10k is usually a good choice, although it varies depending on the model and the dataset.  (Maybe you already saw this in the paper since you mentioned it, but [Figure 4](https://aka.ms/hb-paper) might give you a rough idea of batch sizes to try.)

Right now we feed larger batches in manually (ex: loop).  Automatic batching would be an awesome feature, agreed!

**Comment by interesaaat** [comment]
Should we open a new issue on this (adding batching to the pytorch container)?. We can add a batching parameter which, if set, will be used within the container to batch the records.

**Comment by ksaur** [comment]
This seems easy enough to implement, and would be a very useful feature, so I'll open an issue!

How common is batching help (automatic or in other libraries)?  The IPU/PopArt code I worked with had some nice batching features, but I'm sure about other frameworks

**Comment by zhanjiezhu** [comment]
thanks for adding an issue! I'll close this one then as this is not really a bug.
