### ISSUE TITLE
Lightgbm model with ONNX backend is too slow in comparison to one with torch backend

### ISSUE THREAD

**Issue by KranthiGV** [microsoft/hummingbird#199]
The notebook `LGBM-ONNX-example` [(URL)](https://github.com/microsoft/hummingbird/blob/master/notebooks/LGBM-ONNX-example.ipynb) can be improved in several ways:
1. Add handy 'pip install' commands cell similar to other notebooks (for improving experience in Google Colab)
2. The example has high memory usage and also takes longer to run than the lightgbm's pytorch backend example.
- The memory usage is higher than 16 GB and when run in Colab, etc, the kernel is killed.
- Similarly, the execution time also increases rapidly as we increase the number of samples.
- The above observations may be like that by design or may indicate a memory leak or inefficient implementations.
**Or is it some other factor? Any ideas welcome here. :)**
3. Fix typos in some of the cells (`innitial_types` vs `input_types`) so the users can execute the example.

Till we investigate and address the point 2, I propose that we reduce the number of samples in the example provided in the notebook so that it can be run in most systems that our users may use.

**Comment by KranthiGV** [comment]
Meanwhile...I have been profiling this a little for various sample sizes [ X.shape = (sample_size, 28) ; y.shape = (sample_size) ]. Each cell shows time in seconds.

| sample_size / method  	|  1000 	|  5000 	| 10000 	|  50000 	| 100000 	|
|-----------------------	|------:	|------:	|------:	|-------:	|-------:	|
| convert               	| 0.748 	| 1.658 	| 3.173 	| 12.508 	| 25.141 	|
| ort.InferenceSession  	| 0.073 	| 0.194 	| 0.315 	|  1.847 	|  5.136 	|
| session.run           	| 0.208 	| 1.317 	| 2.945 	| 12.985 	| 26.554 	|

It is interesting to note that the convert call also takes long time. Most of the time is spent in `torch.index_select` method.

**Comment by interesaaat** [comment]
Thanks @KranthiGV for reporting this. I think that this is a problem with the ONNX converter in PyTorch \ ONNX runtime. I think it would be great if we can investigate a bit and open an issue against ONNX directly. +1 or reducing the number of samples for the moment to make the notebook usable, but yes, we should ask the ONNX folks to look into this.

**Comment by interesaaat** [comment]
For instance can you do a comparison between the pytorch memory \ run time vs ONNX so that we can point the ONNX team to the right direction? For pytorch please use the `tree_trav` strategy since there is a bug in the ONNX exporter in PyTorch and `GEMM` does not work at the moment.

**Comment by KranthiGV** [comment]
Yes, as you said, the problem seems to be in onnx converter. Thanks for the pointers here. I will do the comparison first and we can then file a bug appropriately.

**Comment by KranthiGV** [comment]
Created #207 to address a part of this issue.
Will get to the bottom of additional profiling needed as well.

**Comment by interesaaat** [comment]
I did some profiling, and it looks that the problem is that the default opset (9) used to export into ONNX produces bad models. With opset 11 the performance are quite close to PyTorch  (for GPU at least). Issue #211  should fix the problem.
