### ISSUE TITLE
Simplify convert_sklearn API

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#20]
In its current implementation to convert a sklearn model we have something like:
```python
convert_sklearn(model, initial_types=[('input', FloatTensorType([4, 3]))])
```
but we actually don't need the specification of input types (this is more a onnx converter thing). So we can have something like:
```python
convert_sklearn(model)
```
which is nice and short. The problem with this is that XGBoostRegressor models do not surface information on the number of input features (while instead XGBoostClassifier does). Then if we go with the above API we will need a workaround for XGBoostRegressor. One possibility is to have the following specifically for XGBoostRegression models:
```python
extra_config["n_features"] = 200
pytorch_model = convert_sklearn(model, extra_config=extra_config)
```
Another possibility is to pass some input data as for other converters:
```python
pytorch_model = convert_sklearn(model, some_input_data)
```
One last possibility is to have a different API for each converter (Sklearn, LightGBM and XGBoost; as ONNXMLTools are doing right now). The for Sklearn we will have:
Another possibility is to pass some input data as for other converters:
```python
pytorch_model = convert_sklearn(model)
```
For LightGBM we will have
Another possibility is to pass some input data as for other converters:
```python
pytorch_model = convert_lightgbm(model)
```
And for XGboost we will have either to pass an extra param or the input data. For example:
```python
pytorch_model = convert_xgboost(model, some_input_data)
```

**Comment by interesaaat** [comment]
@ksaur WDYT?

**Comment by ksaur** [comment]
I think i like the `pytorch_model = convert_lightgbm(model)` and `pytorch_model = convert_xgboost(model, some_input_data)` option best. It seems to make more sense overall.

(discussed in chat but adding here for the record)
