### ISSUE TITLE
 Improving lightgbm ONNX backend example : Reduce sample size to make nb usable

### ISSUE THREAD

**Issue by KranthiGV** [microsoft/hummingbird#207]
Issue to track addressing a few issues discussed in #199 
1. Add handy 'pip install' commands cell similar to other notebooks (for improving experience in Google Colab)
2. Fix typos in some of the cells (innitial_types vs input_types) so the users can execute the example.
3. Reducing the number of samples for the moment to make the notebook usable.

**Comment by ksaur** [comment]
Thanks @KranthiGV for listing these out!! 
Is this something you want to work on/shall I assign it to you?

**Comment by KranthiGV** [comment]
Yes, raising a PR in a while.
