### ISSUE TITLE
warnings.filterwarnings("ignore") in tests is not working.

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#21]
Apparently I am still getting a lot of warning when running tests.

**Comment by ksaur** [comment]
This warning-suppression does not work in vscode, but works fine in a proper terminal. At least that was my experience.

the warning-suppression also works fine in the github-actions outputs i think; look to see if it's not what you expect

**Comment by interesaaat** [comment]
I see. Yes it needs to be a "proper terminal" because even from VSCode terminal it does not work.

**Comment by interesaaat** [comment]
Closing since this is a vscode issue.

**Comment by ksaur** [comment]
I found this https://stackoverflow.com/questions/52224813/python-warnings-filterwarnings-does-not-ignore-deprecationwarning-from-import-s
in case we issues outside vscode

**Comment by interesaaat** [comment]
Ah this is interesting. Should we set that loggingCaptureWarning thing by default in the tests?
