### ISSUE TITLE
Rounding in small datasets

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#22]
With small datasets, often get a rounding error that we don't see with larger datasets

repro:
```python
import numpy as np
import torch, pickle
from hummingbird import convert_sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris


data = load_iris()
X, y = data.data, data.target
X_torch = torch.from_numpy(X)


model = RandomForestClassifier(n_estimators=10)
model.fit(X, y)
pytorch_model = convert_sklearn(
    model, 
    extra_config = {"tree_implementation": "perf_tree_trav"})

skl = model.predict_proba(X)

pytorch_model.to('cuda')
hum_gpu = pytorch_model(X_torch.to('cuda'))

np.testing.assert_allclose(skl, hum_gpu[1].data.to('cpu').numpy(), rtol=1e-06, atol=1e-06)
```

you get 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1533, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 846, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=1e-06

Mismatched elements: 10 / 450 (2.22%)
Max absolute difference: 0.1
Max relative difference: 1.
 x: array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],...
 y: array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],...
```

**Comment by ksaur** [comment]
I was digging into this a bit to see if there is some easy fix.   On [line 98 of random_forest.py](https://github.com/microsoft/hummingbird/blob/develop/hummingbird/operator_converters/random_forest.py#L98) , in one test example, one line was `[0.0, 0.7000, 0.3000]`, (expected value from skl: `[0.    0.6 0.4]`) then after argmax on line 103, it is still the same value, so the error has to be further up (not a problem with the `argmax` at this point at least).  

In other places, the mismatch is a bit more (expected `[0.    0.3 0.7]`, got `[0.0, 0.1000,   0.9000]`)

Maybe something is wrong with [values/thresholds in this loop?](https://github.com/microsoft/hummingbird/blob/develop/hummingbird/operator_converters/_tree_commons.py#L320)?

**Comment by ksaur** [comment]
Another example in this [notebook](https://github.com/microsoft/hummingbird/blob/ksaur/notebooks_and_tests_/notebooks/scikit-learn-random-forest-example.ipynb), see how it only passes with `atol=1e-1`

**Comment by ksaur** [comment]
See also this failed run: https://github.com/microsoft/hummingbird/runs/572459446

**Comment by interesaaat** [comment]
This latest one could be related to #10.

**Comment by interesaaat** [comment]
This is a duplicate of #30. Will close this.
