### ISSUE TITLE
Add support for Pandas Dataframes

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#252]
In Hummingbird we currently support `ndarrays` as input. We should add support for Pandas `Dataframes` too. This is particularly critical for pipelines since each operator in a pipelines can work on a set of columns on the dataframe. This will require extracting schema information from the dataframe.

**Comment by scnakandala** [comment]
> each operator in a pipelines can work on a set of columns on the dataframe

@interesaaat  Will the columns be referenced by the index or by the column name?
I remember there are some operators like ColumnTranformer which refer columns by index.
I think these cases should be easy to support by simply converting the dataframe to numpy (df.to_numpy())

**Comment by interesaaat** [comment]
Yes this is exactly what we have right now. It would be good to extend it to support dataframes more in general.
