### ISSUE TITLE
running hummingbird.ml in conda

### ISSUE THREAD

**Issue by sephib** [microsoft/hummingbird#314]
Hi,
Are you planning to publish hummingbird as a conda package (recipe) in anaconda?

**Comment by interesaaat** [comment]
Hi @sephib, no plan on this yet.

**Comment by sephib** [comment]
Do you mind if I publish `onnxconverter` and  `hummingbird.ml` to anaconda?

**Comment by interesaaat** [comment]
Hey @sephib, I don't see any problem with that! Thanks! You might want to ask the `onnxconverter` folks if they are ok with it (for the `onnxconverter` side)

**Comment by xhochy** [comment]
This is now available via conda-forge: https://github.com/conda-forge/hummingbird-ml-feedstock

**Comment by interesaaat** [comment]
This is a great news! Thanks @xhochy.
