### ISSUE TITLE
Bug in scikit-learn multinomial_naive_bayes?

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#352]
The tests for sklearn_multinomial_naive_bayes  are currently failing.  See #351 

```
Mismatched elements: 126 / 300 (42%)
Max absolute difference: 5.14276043e-05
Max relative difference: 0.00016642
 x: array([[0.2135  , 0.515825, 0.270674],
       [0.57376 , 0.197127, 0.229113],
       [0.568936, 0.205431, 0.225633],...
 y: array([[0.213498, 0.515857, 0.270662],
       [0.573796, 0.197128, 0.229092],
       [0.568949, 0.205432, 0.225623],...
```

**Comment by ksaur** [comment]
@scnakandala is this something you have time to take a look at? :)

**Comment by interesaaat** [comment]
In the worst case we can increasing the abs error.

**Comment by ksaur** [comment]
Yes, setting `atol=1e-5` to `atol=1e-4` fixes it, but wanted to make sure nothing else was off.

**Comment by interesaaat** [comment]
Yep, agreed. This should be the last resort.

**Comment by ksaur** [comment]
Thank you so much @scnakandala !
