### ISSUE TITLE
Training on XGB versions > 0.90 on Pandas breaks the converter

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#356]
When using XGBoost version > 0.90 over a pandas dataframe, the tree representation contains the column labels instead of indexes. This breaks our converter. A temporary workaround is to just train over numpy arrays, but on the long term, we should fix our tree-parser logic to address also this case.

**Comment by ksaur** [comment]
I think that #523 closed this, can you confirm @interesaaat ?

**Comment by interesaaat** [comment]
I am not sure if that specific PR fixed this, but indeed we don't have anymore problems with xgb > 0.90, so we can clone this.
