### ISSUE TITLE
Cannot use torch==1.5.0  due to breaking change

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#37]
When using torch==1.5.0 (instead of the current torch==1.4.0), hummingbird sometimes gets stuck in an infinte loop in `forward`:

```bash
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/hummingbird/hummingbird/operator_converters/_tree_implementations.py", line 349, in forward
    gather_indices = torch.index_select(nodes, 0, prev_indices).view(-1, self.num_trees)
```

This is potentially due to this **[BC-BREAKING] change index_select scalar_check to retain dimensionality of input. #30790](https://github.com/pytorch/pytorch/pull/30790)** in torch==1.5.0 in the `index_select`  function.  The change makes it so they return a 0-dimensional tensor iff the input is 0-dimensional.

However, after digging around a bit more in our code, I separated out 
```python
 gather_indices = torch.index_select(nodes, 0, prev_indices).view(-1, self.num_trees)
```
into:
```python
gather_indices = torch.index_select(nodes, 0, prev_indices)  #  now gets stuck here
if gather_indices.shape == torch.Size([]):
    gather_indices = gather_indices.view(-1)
gather_indices = gather_indices.view(-1, self.num_trees)
```

and found that the code is getting stuck on the `index_select` itself rather than any problem with the changed return type.

So maybe there is some issue related to **[optimize index_select performance on CPU with TensorIterator #30598](https://github.com/pytorch/pytorch/pull/30598)**, also new in torch==1.5

**Comment by interesaaat** [comment]
We are already at pytorch 1.6.0. Closing this since not relevant anymore.
