### ISSUE TITLE
MissingConverter : Unable to find converter for model type <class 'sklearn.pipeline.Pipeline'>

### ISSUE THREAD

**Issue by smilenrhyme** [microsoft/hummingbird#370]
Getting below error : Is this expected, please assist. thanks a lot !!

`` **MissingConverter**                          Traceback (most recent call last)
<ipython-input-283-85599cede8e0> in <module>
----> 1 h_model = convert(pi_clf_pipeline, 'pytorch')

/venv/lib/python3.6/site-packages/hummingbird/ml/convert.py in convert(model, backend, test_input, device, extra_config)
    393         return _convert_sparkml(model, backend, test_input, device, extra_config)
    394 
--> 395     return _convert_sklearn(model, backend, test_input, device, extra_config)

/venv/lib/python3.6/site-packages/hummingbird/ml/convert.py in _convert_sklearn(model, backend, test_input, device, extra_config)
     86     # We modify the scikit learn model during translation.
     87     model = deepcopy(model)
---> 88     topology = parse_sklearn_api_model(model, extra_config)
     89 
     90     # Convert the Topology object into a PyTorch model.

/venv/lib/python3.6/site-packages/hummingbird/ml/_parse.py in parse_sklearn_api_model(model, extra_config)
     58     # Parse the input scikit-learn model into its scope with the topology.
     59     # Get the outputs of the model.
---> 60     outputs = _parse_sklearn_api(scope, model, inputs)
     61 
     62     # Declare output variables.

/venv/lib/python3.6/site-packages/hummingbird/ml/_parse.py in _parse_sklearn_api(scope, model, inputs)
    222     tmodel = type(model)
    223     if tmodel in sklearn_api_parsers_map:
--> 224         outputs = sklearn_api_parsers_map[tmodel](scope, model, inputs)
    225     else:
    226         outputs = _parse_sklearn_single_model(scope, model, inputs)

/venv/lib/python3.6/site-packages/hummingbird/ml/_parse.py in _parse_sklearn_pipeline(scope, model, inputs)
    268     """
    269     for step in model.steps:
--> 270         inputs = _parse_sklearn_api(scope, step[1], inputs)
    271     return inputs
    272 

/venv/lib/python3.6/site-packages/hummingbird/ml/_parse.py in _parse_sklearn_api(scope, model, inputs)
    222     tmodel = type(model)
    223     if tmodel in sklearn_api_parsers_map:
--> 224         outputs = sklearn_api_parsers_map[tmodel](scope, model, inputs)
    225     else:
    226         outputs = _parse_sklearn_single_model(scope, model, inputs)

/venv/lib/python3.6/site-packages/hummingbird/ml/_parse.py in _parse_sklearn_feature_union(scope, model, inputs)
    302     # Encode each transform as our IR object
    303     for name, transform in model.transformer_list:
--> 304         transformed_result_names.append(_parse_sklearn_single_model(scope, transform, inputs)[0])
    305         if model.transformer_weights is not None and name in model.transformer_weights:
    306             transform_result = [transformed_result_names.pop()]

/venv/lib/python3.6/site-packages/hummingbird/ml/_parse.py in _parse_sklearn_single_model(scope, model, inputs)
    244         raise RuntimeError("Parameter model must be an object not a " "string '{0}'.".format(model))
    245 
--> 246     alias = get_sklearn_api_operator_name(type(model))
    247     this_operator = scope.declare_local_operator(alias, model)
    248     this_operator.inputs = inputs

/venv/lib/python3.6/site-packages/hummingbird/ml/supported.py in get_sklearn_api_operator_name(model_type)
    353     """
    354     if model_type not in sklearn_api_operator_name_map:
--> 355         raise MissingConverter("Unable to find converter for model type {}.".format(model_type))
    356     return sklearn_api_operator_name_map[model_type]
    357 

**MissingConverter**: Unable to find converter for model type <class 'sklearn.pipeline.Pipeline'>.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter implemented.``

**Comment by ksaur** [comment]
Hi @smilenrhyme ! Can you please share some of your code that you used to create the model/pipeline?  That will help us understand a bit more about what `"Parameter model must be an object not a " "string '{0}'.".format(model)` might mean for example.

**Comment by smilenrhyme** [comment]
Hi @ksaur , Thanks a lot for the quick response :)

Sorry for delay in the reply. Below is the code in brief

```
# Custom classes
class MissingValueImputer(BaseEstimator, TransformerMixin):
class DFSubsetSelector(BaseEstimator,TransformerMixin):

f1_extractor = Pipeline([('selector', DFSubsetSelector(some_features)),
                         ('fill_na', MissingValueImputer(columns=some_features, fill_types=['median'] * len(some_features)))
                         ])

# feature_extractor : "FeatureUnion" over multiple scikit style custom transformers
feature_extractor = FeatureUnion(transformer_list=[
                                                    ('extractor1', f1_extractor),
                                                    ('extractor2', f2_extractor)])

learner = lgb.LGBMRanker()

# pipeline : this is scikit-learn pipeline
pipeline = Pipeline([('feature_extractor_preprocessor',feature_extractor),
                         ('learner',learner)])
```

=> This is failing 
convert(pipeline, 'pytorch')

=> This is working fine when I extract only ligtgbm model from pipeline
lgbm_model = pipeline.named_steps['learner']
h_model = convert(lgbm_model, 'pytorch')

Note : hummingbird-ml==0.1.0

Please let me know if you need other details 👍

**Comment by ksaur** [comment]
Hi @smilenrhyme  Thanks for posting this so we have another datapoint! We don't yet support custom classes inside pipelines, (and I also think we don't support nested pipelines) so the error you're getting is expected as of right now.  

This issue is similar to the recently posted #371 feature request.  This is on our list of things to implement!

**Comment by smilenrhyme** [comment]
@ksaur Thanks a lot 👍 Closing this issue for now :)
