### ISSUE TITLE
Numpy install error

### ISSUE THREAD

**Issue by ThomasWolf0701** [microsoft/hummingbird#372]
I tried to install hummingbird with pip and it tried to downgrade numpy to an old version, and gives an error.

Would it be possible to install via conda ?

WARNING: Error parsing requirements for numpy: [Errno 2] No such file or directory: 'c:\\users\\thomas wolf\\anaconda3\\envs\\my-rdkit-env\\lib\\site-packages\\numpy-1.19.4.dist-info\\METADATA'
Installing collected packages: numpy, onnx, onnxconverter-common, hummingbird-ml
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.4
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\users\\thomas wolf\\anaconda3\\envs\\my-rdkit-env\\lib\\site-packages\\numpy-1.19.4.dist-info\\RECORD'

**Comment by ksaur** [comment]
Hi @ThomasWolf0701 ! We don't currently have hummingbird in conda (see #314).

I think the easiest way to install Hummingbird if it conflicts with an existing `numpy` installation would be to create a fresh virtual environment.  Does that work for you?

**Comment by ksaur** [comment]
closed with #390
