### ISSUE TITLE
Type Error when using a Pipeline with StandardScaler and PCA (+RandomForestRegressor)

### ISSUE THREAD

**Issue by speedfreakw** [microsoft/hummingbird#388]
I'am getting a type error if I'm trying to use an Pipeline consisting of an StandardScaler, an PCA and an RandomForestRegressor.

The prediction before converting the model to pytorch works fine, but after converting it to pytorch the prediction raises an type Error.

Here is the short code snipped that I run:
```
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from hummingbird.ml import convert
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
import torch

X, y = make_regression(n_samples = 1000, n_features=8, n_informative=5, n_targets=1, random_state=0, shuffle=True)
pca = PCA(n_components=8, svd_solver='randomized', whiten=True)
clf = make_pipeline(StandardScaler(), pca, RandomForestRegressor(n_estimators=10, max_depth=30, random_state=0))
clf.fit(X, y)

prediction = clf.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]) # works
print(prediction)

model = convert(clf, 'pytorch')

prediction = model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]) # raises Error
print(prediction)

```

At the line `prediction = model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])` I get following Error:
>RuntimeError: expected scalar type Double but found Float 

Full Stacktrace:
> Traceback (most recent call last):
>   File "D:/Repositories/masterarbeit/RandForest_Test/Hummingbird_test.py", line 19, in <module>
>     prediction = model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_container.py", line 171, in predict
>     return self._run(self._predict, *inputs)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_container.py", line 85, in _run
>     return function(*inputs)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_container.py", line 262, in _predict
>     return self.model.forward(*inputs).cpu().numpy().ravel()
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_topology.py", line 469, in forward
>     pytorch_outputs = pytorch_op(*(variable_map[input] for input in operator.input_full_names))
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\operator_converters\_decomposition_implementations.py", line 30, in forward
>     return torch.mm(x, self.transform_matrix)
> RuntimeError: expected scalar type Double but found Float

**Comment by interesaaat** [comment]
Thanks for reporting this. We recently merged a PR dealing with doubles, and perhaps we introduced this bug. I will take a look, seems an easy fix.
