### ISSUE TITLE
Runtime Error running HistGradientBoostingRegressor on GPU

### ISSUE THREAD

**Issue by speedfreakw** [microsoft/hummingbird#393]
I'm getting an Runtime Error, if I'm trying to run an HistGradientBoostingRegressor on an CUDA GPU.

> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Here is the short code snippet that I run to produce this Error:
```
from sklearn.datasets import make_regression
from hummingbird.ml import convert
from sklearn.ensemble import HistGradientBoostingRegressor

X, y = make_regression(n_samples=1000, n_features=8, n_informative=5, n_targets=1, random_state=42, shuffle=True)
clf = HistGradientBoostingRegressor(random_state=42)
clf.fit(X, y)

prediction_sk = clf.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
print("Prediction sk: ", prediction_sk)

model = convert(clf, 'pytorch')

prediction_pt_cpu = model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
print("Prediction pt CPU: ", prediction_pt_cpu)

model.to('cuda')

prediction_pt_gpu = model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
print("Prediction pt GPU: ", prediction_pt_gpu)
```
At the line `prediction_pt_gpu = model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])` I get following Error:
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Full Traceback:

> Traceback (most recent call last):
>   File "D:/Repositories/masterarbeit/RandForest_Test/Hummingbird_test.py", line 19, in <module>
>     prediction_pt_gpu = model.predict([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_container.py", line 256, in predict
>     return self._run(self._predict, *inputs)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_container.py", line 83, in _run
>     return function(*inputs)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_container.py", line 349, in _predict
>     return self.model.forward(*inputs).cpu().numpy().ravel()
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\_topology.py", line 475, in forward
>     pytorch_outputs = pytorch_op(*(variable_map[input] for input in operator.input_full_names))
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\operator_converters\_tree_implementations.py", line 246, in forward
>     output = self.aggregation(output)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\operator_converters\_tree_implementations.py", line 522, in aggregation
>     return self.post_transform(output)
>   File "D:\Repositories\masterarbeit\venvPycharm\lib\site-packages\hummingbird\ml\operator_converters\_gbdt_commons.py", line 115, in apply
>     x += base_prediction
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by interesaaat** [comment]
Interesting. I am worried that for some reason the data is not transferred to GPU. Let me test it and I will get back to you. If you do `model = convert(clf, 'pytorch', device='cuda')` does it work?

**Comment by speedfreakw** [comment]
> Interesting. I am worried that for some reason the data is not transferred to GPU. Let me test it and I will get back to you. If you do `model = convert(clf, 'pytorch', device='cuda')` does it work?

No that also doesn't work. Same error

**Comment by interesaaat** [comment]
I found the problem. I am sending a PR right now.

**Comment by speedfreakw** [comment]
When using the extra_config `{"tree_implementation": "gemm"}` or `{"tree_implementation": "perf_tree_trav"}` the Error still remains. But the extra_config `{"tree_implementation": "tree_trav"}` which is the default works now.

`model = convert(clf, 'pytorch', extra_config={"tree_implementation": "gemm"})`
`model = convert(clf, 'pytorch', extra_config={"tree_implementation": "perf_tree_trav"})`

**Comment by ksaur** [comment]
Hi @speedfreakw, thanks so much for finding all of these! Please let us know if this doesn't work or if you run into more issues!

**Comment by speedfreakw** [comment]
I am the one to thank. The speed with which you have fixed all the bugs I've found is incredible! Furthermore, Hummingbird is an amazing converter and helps me a lot with my master thesis!

**Comment by interesaaat** [comment]
I was hoping for "The speed ~~with which you have fixed all the bugs I've found~~ of Hummingbird is incredible!" 😄 .

Glad to hear we helped!

**Comment by speedfreakw** [comment]
Haha yes the speed of Hummingbird is also incredible 😄 Currently it cuts the time of the Prediction from 400ms to only 22ms and this is huge!
