### ISSUE TITLE
Did it supports KNN and SVR?

### ISSUE THREAD

**Issue by KIIIIK** [microsoft/hummingbird#421]
if i use sklearn KNN training my model , it takes too long, so i want to know weather i can use this lib to fit my model

**Comment by ksaur** [comment]
Hi @KIIIIK 

Hummingbird only works for inference/scoring...you must have created and trained the model ahead of time in scikit-learn before converting.  For inference, we do support SKL's KNN: KNeighborsClassifier and KNeighborsRegressor (list of supported operators is [here](https://github.com/microsoft/hummingbird/wiki/Supported-Operators#classifiers-other)).

If the inference case is useful to you, see our [test code](https://github.com/microsoft/hummingbird/blob/main/tests/test_sklearn_kneighbors.py) on how to us Hummingbird to convert your already trained sklearn KNN model.
