### ISSUE TITLE
RuntimeError: Hummingbird requires explicit specification of batch_size parameter when compiling KNeighborsClassifier

### ISSUE THREAD

**Issue by KIIIIK** [microsoft/hummingbird#422]
`from hummingbird.ml import convert
knn_model = KNeighborsRegressor()
model = convert(knn_model, 'pytorch')
model.to('cuda')
model.fit(X_train, y_train)`

this code is error, where i should add batch_size ?what should i do ?thanks

**Comment by interesaaat** [comment]
Hi! In this specific case you can do something like (if you want a batch size of 10):
```
import humminbird.ml.constants
extra_config = {hummingbird.ml.operator_converters.constants.BATCH_SIZE: 10}
hb_model = hummingbird.ml.convert(knn_model, "tpyorch", extra_config=extra_config)
```

**Comment by ksaur** [comment]
Closing with #457 issue
