### ISSUE TITLE
fit and convert

### ISSUE THREAD

**Issue by KIIIIK** [microsoft/hummingbird#423]
In sklearn, my model fit is too long(such as KNN).I want to use this lib. But i find it must fit before convert. If i want to sppedup fit, what should i do ,please!
Can i convert first and then fit?

**Comment by scnakandala** [comment]
@KIIIIK Can you provide us an example code snippet to recreate your problem? We can then have a look into what we can do from the Hummingbird side to optimize your pipeline.

**Comment by amirhszd** [comment]
I am having the same problem, the introduced pipeline calls for a fit sk-learn model, I am interested in using an untrained sk learn model and fit my model using Hummingbird. If an untrained model is passed to hummingbird below error is the ouput:

`AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'`

**Comment by interesaaat** [comment]
Hi @yxoos, unfortunately Hummingbird only works with trained pipelines. With KNN we could maybe also work if the model is not trained, but in general (e.g., with RandomForests) this won't work.

**Comment by ksaur** [comment]
@KIIIIK do you have an updated code snippet? 

Maybe untrained KNN works, but otherwise I think we should close this issue with a PR adding a bit more in our documentation to explain that Hummingbird can only handle trained models! :)

**Comment by KIIIIK** [comment]
@ksaur Sorry, I don't use this model now,very thanks you for answer my question.

**Comment by ksaur** [comment]
Closing with #457 issue
