### ISSUE TITLE
Need error messages and documentation that you must "fit" before convert

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#457]
In issue #422/#423, users brought up that it's not clear from the error messages that you must fit before convert for most models.

We suspect that with KNN we could maybe also work if the model is not trained, but in general (e.g., with RandomForests) this won't work.

We need help documenting this, and also generating proper error messages.  (You can see an example of an unhelpful error message in #423.)

**Comment by SangamSwadiK** [comment]
@ksaur Hi, First time contributor to hummingbird, Can I please take up this issue ?
Thanks.
