### ISSUE TITLE
incorrect import statement in example code

### ISSUE THREAD

**Issue by rathijit** [microsoft/hummingbird#465]
The import statement on line 3 in the example code should be changed to "import hummingbird.ml", or to "from hummingbird.ml import convert, load" with just "load" on the last line.

**Comment by ksaur** [comment]
Good catch, thanks!  We added the `load` function recently.

I am happy to fix this, or would you prefer to submit a PR? :)

**Comment by rathijit** [comment]
OK, I will try submitting a PR -- will be my first PR for this project and repo :)

**Comment by interesaaat** [comment]
Don't worry, we are nice :)

**Comment by ksaur** [comment]
Closed with #467, thanks @rathijit!
