### ISSUE TITLE
ONNX and PyTorch model from RandomForestClassifier have different prediction results

### ISSUE THREAD

**Issue by univerone** [microsoft/hummingbird#474]
When I try to convert a RandomForestClassifier model to ONNX and Pytorch format, the prediction results from these two models fail to match, here is the example code

```python
import numpy as np
import onnxruntime as ort
import torch
from hummingbird.ml import convert
from onnxconverter_common import FloatTensorType
from onnxmltools import convert_sklearn
from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier

X_bc, y_bc = load_breast_cancer(return_X_y=True)
nrows = 15000
X_bc: np.ndarray = X_bc[0:nrows]
y_bc: np.ndarray = y_bc[0:nrows]

if __name__ == "__main__":
    sklearn_model = RandomForestClassifier(n_estimators=10, max_depth=10)
    sklearn_model.fit(X_bc, y_bc)

    sample_input = torch.rand(100, X_bc.shape[1], dtype=torch.float32)
    sklearn_model_predict = sklearn_model.predict(sample_input.numpy())

    onnx_ml_model = convert_sklearn(
        sklearn_model, initial_types=[("input", FloatTensorType([sample_input.shape[0], sample_input.shape[1]]))],
        target_opset=11
    )
    session = ort.InferenceSession(onnx_ml_model.SerializeToString())
    output_names = [session.get_outputs()[i].name for i in range(len(session.get_outputs()))]
    inputs = {session.get_inputs()[0].name: sample_input.numpy()}
    onnx_ml_model_pred = session.run(output_names, inputs)[0].flatten()

    pt_model = convert(sklearn_model, "torch", X_bc)
    pt_model_pred = pt_model.predict(sample_input)

    np.testing.assert_allclose(onnx_ml_model_pred, pt_model_pred, rtol=1e-5, atol=0)
```

and here is the output

```
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=0

Mismatched elements: 9 / 100 (9%)
Max absolute difference: 1
Max relative difference: 1.
 x: array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
 y: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
```

**Comment by interesaaat** [comment]
9% is indeed a big difference. I will look into this. Did you try to compare against the skl model, just to double check that the problem is hummingbird, not onnx.

**Comment by scnakandala** [comment]
I tested the provided example code and on my setup and it passed. @univerone Can you also provide the library versions that you using?

**Comment by univerone** [comment]
> I tested the provided example code and on my setup and it passed. @univerone Can you also provide the library versions that you using?

I'm using 
- hummingbird-ml 0.2.2
- onnxmltools 1.7.0
- sklearn 0.23.2
- torch 1.5.0
- onnxruntime 1.2.0
- onnxconverter_common 1.7.0

**Comment by univerone** [comment]
> 9% is indeed a big difference. I will look into this. Did you try to compare against the skl model, just to double check that the problem is hummingbird, not onnx.

I have tried and found that sklearn model has the same prediction results as ONNX model, but different from torch model

**Comment by interesaaat** [comment]
@univerone can you please try with the latest version of PyTorch? In earlier versions `argmax` had some weird behavior (see [here](https://github.com/microsoft/hummingbird/issues/10)).

**Comment by scnakandala** [comment]
I tested on different torch versions.
On torch==1.5.0 the test fails. But, it passes on torch==1.7.0.

**Comment by ksaur** [comment]
Yes as Matteo says, it seems this is related to #10, where we know this mismatch occurs in torch<1.7.0.

What would be the best way to handle it?  Print a  warning for older torch versions?

**Comment by interesaaat** [comment]
Or we can ditch PyTorch < 1.7 directly? Maybe this is too drastic, WDYT? Adding a warning is easy too since this happens specifically for multiclass.
