### ISSUE TITLE
GridsearchCV hummingbird

### ISSUE THREAD

**Issue by petrojeff** [microsoft/hummingbird#479]
Is there a way to use hummingbird on gridsearch instead of fitting each iteration of the model? Thank you.

AdaBoost_pipe = make_pipeline(
    StandardScaler(),
    AdaBoostRegressor(random_state=10)
)
AdaBoost_default_cv_results = cross_validate(AdaBoost_pipe, X_train, y_train, cv=5)
AdaBoost_grid_cv = GridSearchCV(AdaBoost_pipe, param_grid=grid_params, cv=5, n_jobs=-1)
AdaBoost_grid_cv.fit(X_train, y_train)

**Comment by interesaaat** [comment]
Do you mean using Hummingbird for speeding up the `fit` method? I don't think we can help at the moment because we don't support training.

**Comment by petrojeff** [comment]
Hi Matteo thank you for your response. Is this something you plan to support in the future? Thank you.

**Comment by interesaaat** [comment]
He have some initial idea (e.g., [here](https://arxiv.org/abs/1906.03822)) but we have not currently scheduled any work on this, so it might take some time.

**Comment by interesaaat** [comment]
Closing for the moment.
