### ISSUE TITLE
Add support for SHAP package

### ISSUE THREAD

**Issue by seuzha** [microsoft/hummingbird#480]
SHAP is a general model attrition package: https://fburl.com/5lq7ho5y

I have a use case to first use SHAP to explain a sklearn/xgboost classifier and then convert the model to pytorch. SHAP is not supported yet for model conversion. Is there a quick way to walk it around?

**Comment by interesaaat** [comment]
Hi @seuzha! We were looking into it (see #180) but we didn't make much progress. Do you want to give it a shot?

**Comment by ksaur** [comment]
Closing as a duplicate of #180 .  @seuzha, if you feel inspired to work on this, please let us know and I'll repoen!! :)
