### ISSUE TITLE
sklearn random forest classifier hb model throws mismatch inputs

### ISSUE THREAD

**Issue by indiangolfer** [microsoft/hummingbird#481]
AssertionError: number of inputs or number of columns in the dataframe do not match with the expected number of inputs ['input']

sklearn model works correctly:

# Load from sklean model file
with open('sklearn_model.pkg', 'rb') as file:
    RF_model = pickle.load(file)

predicted_proba = RF_model.predict_proba(sample_input) # this works correctly

HB_model = convert(RF_model, 'pytorch')
HB_predicted_proba = HB_model.predict_proba(sample_input) # this throws the AssertionError

# ------------------ Stack ----------------
  File "xxxx/.virtualenvs/HBTest/lib/python3.8/site-packages/hummingbird/ml/containers/_sklearn_api_containers.py", line 114, in predict
    return self._run(self._predict, *inputs)
  File "xxxx/.virtualenvs/HBTest/lib/python3.8/site-packages/hummingbird/ml/containers/_sklearn_api_containers.py", line 62, in _run
    return function(*inputs)
  File "xxxx/.virtualenvs/HBTest/lib/python3.8/site-packages/hummingbird/ml/containers/sklearn/pytorch_containers.py", line 171, in _predict
    return self.model.forward(*inputs)[0].cpu().numpy().ravel()
  File "xxxx/.virtualenvs/HBTest/lib/python3.8/site-packages/hummingbird/ml/_executor.py", line 67, in forward
    assert len(self._input_names) == len(inputs) or (
AssertionError: number of inputs or number of columns in the dataframe do not match with the expected number of inputs ['input']

**Comment by interesaaat** [comment]
Is sample input a numpy array or a pandas dataframe? If it's the latter, can you try with `sample_input.values`? (By default if no test input is passed to the `convert` model, Hummingbird expects a numpy array at prediction time).

**Comment by indiangolfer** [comment]
Thanks for your comment.  Your assumption was correct, sample_input is a pandas dataframe.  I figured out that I need to pass in numpy array but when I pass in sample_input as numpy array (sample_input.to_numpy()), I get the following when predict_proba is called:

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by indiangolfer** [comment]
Ok, this worked based on https://github.com/yassouali/pytorch_segmentation/issues/31#issuecomment-562510155

sample_input.to_numpy(dtype=np.float32)

Thanks.

**Comment by indiangolfer** [comment]
Closing the issue, please see the above comment.
