### ISSUE TITLE
CI/CD failing for spark due to GH Actions issue

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#493]
Today it seems that we run into
```
E py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext. 
29E : java.net.BindException: Cannot assign requested address: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address. 
30E at sun.nio.ch.Net.bind0(Native Method)
```

when (re)-running the pipeline.  

It does not appear to be something we can fix on our end.  For now, commenting out Spark (#492)  in the pipeline with
```
-       pip install .[extra,onnx,sparkml]
+       pip install .[extra,onnx]
```

This issue is a reminder to put this back when the issue is fixed.

**Comment by ksaur** [comment]
closed with #494

**Comment by lhotari** [comment]
FYI, this seems to be caused by https://github.com/actions/virtual-environments/issues/3185 . Reverse name lookup for current hostname is broken.

**Comment by ksaur** [comment]
Ah!! Thank you so much for the info! We were wondering what went wrong suddenly. :)
