### ISSUE TITLE
What is pytorch container and how do I see the actual matrices?

### ISSUE THREAD

**Issue by marsupialtail** [microsoft/hummingbird#516]
In the example code, how would I go look at the pytorch model container variable model, and find out what actual computations it is computing? Aka how do I convert the pytorch container type to an actual nn.Module in pytorch?

**Comment by ksaur** [comment]
Hello!

From the sample code for example:
```
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from hummingbird.ml import convert, load

# Create some random data for binary classification
num_classes = 2
X = np.random.rand(100000, 28)
y = np.random.randint(num_classes, size=100000)

# Create and train a model (scikit-learn RandomForestClassifier in this case)
skl_model = RandomForestClassifier(n_estimators=10, max_depth=10)
skl_model.fit(X, y)

# Use Hummingbird to convert the model to PyTorch
model = convert(skl_model, 'pytorch')
```

you can then do something like:
```
>>> type(model._model._operators)
<class 'torch.nn.modules.container.ModuleList'>
>>> model._model._operators[0]
PerfectTreeTraversalDecisionTreeImpl(
  (nodes): ParameterList(
      (0): Parameter containing: [torch.LongTensor of size 20]
      (1): Parameter containing: [torch.LongTensor of size 40]
      (2): Parameter containing: [torch.LongTensor of size 80]
      (3): Parameter containing: [torch.LongTensor of size 160]
      (4): Parameter containing: [torch.LongTensor of size 320]
      (5): Parameter containing: [torch.LongTensor of size 640]
      (6): Parameter containing: [torch.LongTensor of size 1280]
      (7): Parameter containing: [torch.LongTensor of size 2560]
      (8): Parameter containing: [torch.LongTensor of size 5120]
  )
  (biases): ParameterList(
      (0): Parameter containing: [torch.FloatTensor of size 20]
      (1): Parameter containing: [torch.FloatTensor of size 40]
      (2): Parameter containing: [torch.FloatTensor of size 80]
      (3): Parameter containing: [torch.FloatTensor of size 160]
      (4): Parameter containing: [torch.FloatTensor of size 320]
      (5): Parameter containing: [torch.FloatTensor of size 640]
      (6): Parameter containing: [torch.FloatTensor of size 1280]
      (7): Parameter containing: [torch.FloatTensor of size 2560]
      (8): Parameter containing: [torch.FloatTensor of size 5120]
  )
)
>>> model._model._operators[0].nodes[0]
Parameter containing:
tensor([22, 25, 13,  0,  5,  5, 25, 23, 12, 18,  7, 11,  5, 18, 27,  3, 15, 18,
        24,  2])
```

to see the internals. Is that what you mean?

**Comment by marsupialtail** [comment]
I thought hummingbird actually converts things to matrix multiplications? I tried to force it to convert to gemm by doing this: model = convert(skl_model,'pytorch',extra_config = {"tree_implementation":"gemm"})
But then, I can't actually see any weight matrices when I do model._model.

**Comment by interesaaat** [comment]
Hey @marsupialtail (Karla is currently off so I am picking this up)! In your case, if you do `model.model._operators[0]` as Karla suggested you should see a bunch of matrixes as `weight_1`, `weight_2` etc.

The code of that particular implementation is [here](https://github.com/microsoft/hummingbird/blob/0ea7c44500467b39f803fb651fe2be027aa8315e/hummingbird/ml/operator_converters/_tree_implementations.py#L88). Hope that it helps!

**Comment by marsupialtail** [comment]
So here is the problem. When I use model = convert(skl_model,'pytorch'), I see a bunch of pytorch weights, but they are called Nodes, which are LongTensors and Biases, which are Floats. I suspect that you are converting it to a Decision Tree, just implemented in Pytorch. I don't see any weight matrices.

When I use convert(skl_model,'pytorch',extra_config = {"tree_implementation":"gemm"}), I see GEMMDecisionTreeImpl() when I run model.model._operators[0]. Can't see any weight matrices either.

**Comment by interesaaat** [comment]
What do you mean you cannot see the weight matrices? 

If I do `print(model.model._operators[0].weight_1)`

I see:
```
Parameter containing:
tensor([[0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], requires_grad=True)
```

**Comment by marsupialtail** [comment]
Ah I see. Thank you! Btw, I noticed that using the gemm strategy with a batch size of 1000 in this case results in a 10x slowdown compared to the tree strategy or sklearn. Is that expected behavior?

**Comment by interesaaat** [comment]
The gemm strategy is only efficient for small trees. If you are using PyTorch, this is also expected, as usually we get the best results with TVM as backend.
