### ISSUE TITLE
conversion from sklearn extratrees very very slow

### ISSUE THREAD

**Issue by marsupialtail** [microsoft/hummingbird#524]
X = np.random.rand(10000, 200)
y = np.random.randint(2, size=10000)
tree = ExtraTreesRegressor(n_jobs=4)
tree.fit(X, y)
convert(tree, 'torch', X,extra_config = {"tree_implementation":"gemm"})

Takes more than 10 minutes on my laptop (and I had to kill it before completion).

Do you know what might be the speed bottleneck? Also can convert be parallelized?

**Comment by interesaaat** [comment]
Gemm works well only on shallow trees, like with depth less than 4. In your case I believe your trees are too deep. Hummingbird by default picks another tree implementation in that case, but you are forcing it to use gemm which is slow in this case.

**Comment by marsupialtail** [comment]
I am not doing predict with the trees. Just the conversion. You mean that conversion speed is slow too?

**Comment by interesaaat** [comment]
The conversion speed should be almost instantaneous for torch. I am worried that by forcing gemm you are creating very large tensors that take forever to generate. Can you try to remove the gemm extra configuration and see if the compilation is faster?

**Comment by marsupialtail** [comment]
Would you mind pointing me to the exact place where the gemm conversion happens for these large trees? Thanks!

**Comment by interesaaat** [comment]
Sure! [Here](https://github.com/microsoft/hummingbird/blob/0bb9b0e63151e30db498616de29b8e3281b8ca0c/hummingbird/ml/operator_converters/_tree_implementations.py#L133).
