### ISSUE TITLE
Fix icon consistency for dark theme

### ISSUE THREAD

**Issue by ronilaukkarinen** [microsoft/hummingbird#528]
Sorry to say but this bugs the hell out of me 😁  Which one doesn't belong:

![Screen-Shot-2021-06-22-23-12-40 74](https://user-images.githubusercontent.com/1534150/122993053-83dd7b80-d3af-11eb-9406-1e89095e5073.png)

Can you change it to be more consistent or add an option for it?

**Comment by ronilaukkarinen** [comment]
Omg... accidentally opened an issue to the wrong repository. It seems there's a lot of hummingbirds out there. I meant [this one](https://github.com/finestructure/Hummingbird)... sorry!

**Comment by ksaur** [comment]
Haha yes we do converters for ML models, not temperatures/icons :-D
