### ISSUE TITLE
Which tools did you use to draw the figures in README?

### ISSUE THREAD

**Issue by WhatAShot** [microsoft/hummingbird#535]
Which tools did you use to draw the figures in README? I think that style is pretty attractive.

**Comment by ksaur** [comment]
The graphics are all done by @vumichien!  We loved his [blog post](https://towardsdatascience.com/standardizing-traditional-machine-learning-pipelines-to-tensor-computation-using-hummingbird-7a0b3168670) and asked for permission to use them. :)  You'll have to reach out to him directly to learn what tools he used.  Thanks!
