### ISSUE TITLE
Torch Tensor output for model.predict(X) after converting basic sklearn ML model

### ISSUE THREAD

**Issue by BaurB** [microsoft/hummingbird#538]
I would like to know whether there is a possibility/there is already a way to have torch.tensor datatype as an output of predict function for converted sklearn model. In current implementation all the prediction outputs has data type of numpy.ndarray. Giving an option of having a torch.tensor  as an output would be nice since your function already converts sklearn model to tensor operations

**Comment by interesaaat** [comment]
Hi! This is currently not possible but I think it shouldn't be too hard to add a configuration flag for this. Going from numpy arrays to tensors however should be 0-copy so you shouldn't see any penalty on doing this externally to Hummingbird.

**Comment by BaurB** [comment]
Thanks for reply!
I am not sure I got a note about 0-copy, can you please show how to do it externally?
My current setup is as follows:

`from sklearn.ensemble import RandomForestRegressor
from hummingbird.ml import convert
random_forest = RandomForestRegressor()
random_forest.fit(X, y) # X and y are from any dataset
random_forest_converted = convert(random_forest,'pytorch')
print(type(random_forest.predict(X))) # gives me type of numpy array
print(type(random_forest_converted.predict(X))) # also gives me type of numpy array, but I want torch tensor for further use
`
Can you please advise/write an external way so that my prediction with converted sklearn model (random_forest_converted) will be not in numpy array, but in tensor format

Thanks in advance

**Comment by interesaaat** [comment]
This should work:
```
import torch
...
output = random_forest_converted.predict(X)
output_tensor = torch.from_numpy(output)
print(output_tensor)
```

**Comment by BaurB** [comment]
Thanks a lot, appreciate your help!

**Comment by imneonizer** [comment]
````python
import torch
...
model_gpu = random_forest_converted.to('cuda')
input_tensor_gpu = torch.from_numpy(output).to('cuda')

model_gpu.predict(input_tensor_gpu)
````

Error:
````sh
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_index_select)
````

The converted model doesn't works on GPU tensors.
