### ISSUE TITLE
loading lightgbm.basic.Booster

### ISSUE THREAD

**Issue by marsupialtail** [microsoft/hummingbird#539]
Is there a way to directly convert a LightGBM booster object instead of using the sklearn API? 

With the sklearn API for lgb, I think you can only load file to a booster object, and I'm not sure how to initialize a lgb regressor from a booster object.

Currently when I try convert booster object directly I get: hummingbird.ml.exceptions.MissingConverter: Unable to find converter for model type <class 'lightgbm.basic.Booster'>.

**Comment by ksaur** [comment]
Right now we only [support](https://github.com/microsoft/hummingbird/wiki/Supported-Operators#lightgbm) direct conversion from LGBM Classifier/Ranker/Regressor, so the error you get is expected.  

I'm not sure how much additional effort it would be to support `lightgbm.Booster`; I'll add it to feature requests list.

Other thoughts @interesaaat ?

**Comment by interesaaat** [comment]
Hey! I think it should be doable. I saw that we get all infos from the `booster_` object.

![image](https://user-images.githubusercontent.com/1534199/129305179-6a07dbd6-b7ee-4ff0-9712-63b2ac71d941.png)

@marsupialtail I think it is a matter of adding LightGBM booster among the supported operators. Do you want to give it a shot?

**Comment by marsupialtail** [comment]
If you point me to a couple places in the code you think would serve as a good reference, I can try to work on this.

**Comment by ksaur** [comment]
@marsupialtail - PR #173 (LGBMRanker) is a good starting point! For Booster, you'll probably need to add a separate converter function in `hummingbird/ml/operator_converters/lightgbm.py`. (For the Ranker one in the PR, it was able to reuse the `convert_sklearn_lgbm_regressor`.)  

I'm not sure what else will be needed, but as Matteo showed above, the information will be there in [line 99](https://github.com/microsoft/hummingbird/blob/main/hummingbird/ml/operator_converters/lightgbm.py#L99).

Please reach out if you get stuck!

**Comment by marsupialtail** [comment]
I made the change locally. How do I contribute to master branch? Can you let me make a PR?

**Comment by marsupialtail** [comment]
I made a PR. Please review. Thanks.

**Comment by alexyar88** [comment]
You can create sklearn object from your booster. Something like that:

```
lgb_clf = lgb.LGBMClassifier(n_estimators=booster.current_iteration())
lgb_clf._Booster = deepcopy(booster)
lgb_clf._n_features = len(booster.feature_name())
lgb_clf._n_classes = len(np.unique(y))
lgb_clf._le = _LGBMLabelEncoder().fit(y)
```
