### ISSUE TITLE
Sklearn Pipeline has None estimator,Convert MissingConverter

### ISSUE THREAD

**Issue by xesdiny** [microsoft/hummingbird#547]
Hi,I used the convert to translate a mutli-ouput sklearn pipeline,Struction as:
![image](https://user-images.githubusercontent.com/21252416/139239405-41cfa12b-4b62-4b58-8196-564b843e8c5f.png)

`scaler` and `selector` maybe is None

Exception result:
```
hummingbird.ml.exceptions.MissingConverter: Unable to find converter for model type <class 'NoneType'>.
```

How can I do about this case?

**Comment by interesaaat** [comment]
Hi! Thanks for reporting this. Can you please share the script you used to
generate the pipeline or a minimum example for reproducing this?

**Comment by ksaur** [comment]
Hi @xesdiny, are you able to share your code so we can check this?

**Comment by ksaur** [comment]
Closing due to timeout, please reopen if required!
