### ISSUE TITLE
Add support for model type sklearn.cross_decomposition._pls.PLSRegression

### ISSUE THREAD

**Issue by christophermwhite5** [microsoft/hummingbird#548]
I was running tests of converting from multiple machine learning algorithms to pytorch using hummingbird.ml, and got a Missing Converter error. Could you please add this to the roadmap?

## Code example:
from sklearn.cross_decomposition import PLSRegression as PLSR
modInstance = PLSR(n_components = 10,).fit(X_train,y_train)
model = convert(modInstance,'pytorch')
pred = model.predict(X_test)

## Error:
**MissingConverter:** Unable to find converter for model type <class 'sklearn.cross_decomposition._pls.PLSRegression'>.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter implemented.

**Comment by interesaaat** [comment]
Hi! Yes we don't support PLSRegression. I will look into it and keep you posted on whether we can add it or not.

**Comment by christophermwhite5** [comment]
Thank you!
