### ISSUE TITLE
Remove implicit deletion of model files from .load() method

### ISSUE THREAD

**Issue by akshjain83** [microsoft/hummingbird#557]
**Issue**
The load() method within `PyTorchSklearnContainer` container class implicitly deletes the original file location provided to the function class. This implicit deletion is unknown to the callers as well as it has side effects that leads to race condition and blocks concurrency setup for our inference servers in production.
 
1. When running inside docker container, deletion of original model file by load method requires docker container restart in order to load model again. That means humming bird model can be loaded only once within docker container lifecycle .
2. We can't run more than one process for inference server, if we do then one process loads it first and deletes the original model file location thus causing race condition for the 2nd process and onwards.

**Desired Behavior**
The `load()` method inside `PyTorchSklearnContainer` class (as well as other as the issue is applicable for all classes) should not delete the original model file location that is supplied by the caller and thus allow multiple time loading as well as running more than one process for inference server.

**Environment**
We are running the inference using a Gunicorn server in front of python app that loads the hummingbird model. The app is containerized as docker image and deployed in Kubernetes Cluster where each pod runs two Gunicorn worker processes to handle concurrency.

**Installed Version**
```
hummingbird-ml==0.4.1
torch==1.5.1
```

Please let me know if you need more information. Thanks.

Regards,
Akshay Jain

**Comment by akshjain83** [comment]
This line in particular causes the issue: https://github.com/microsoft/hummingbird/blob/72a313007e7d9f559ae2b26b0f1fb3c31495387c/hummingbird/ml/containers/sklearn/pytorch_containers.py#L159

**Comment by interesaaat** [comment]
Hi @akshjain83, thanks for reporting this. We decided to delete the temp folders because when you have multiple model versions it can get tricky but indeed I understand your problem when loading multiple models concurrently. 

How about adding an optional flag disabling the deletion of the model? In that way we can still have our default behavior, and in your situations you can just set something like `delete_tmp_folder=False` and leave the temp directory there. WDYT?

**Comment by akshjain83** [comment]
> Hi @akshjain83, thanks for reporting this. We decided to delete the temp folders because when you have multiple model versions it can get tricky but indeed I understand your problem when loading multiple models concurrently.
> 
> How about adding an optional flag disabling the deletion of the model? In that way we can still have our default behavior, and in your situations you can just set something like `delete_tmp_folder=False` and leave the temp directory there. WDYT?

@interesaaat Thanks for getting back. Given the location is provided by the caller to this method, it may or may not be the temporary folder. Its deleting the original model file artifact so I think providing an extra param to control deleting with default value as to delete (keep back compatibility) sounds like a good plan.

Happy to shoot a PR for this. Would you like me to do that?

**Comment by interesaaat** [comment]
Yes! Please go ahead. We love contributions.

**Comment by akshjain83** [comment]
> Yes! Please go ahead. We love contributions.

Sounds good, I am on it.

**Comment by akshjain83** [comment]
@interesaaat Added this PR: https://github.com/microsoft/hummingbird/pull/558

I will move comms to the PR itself on next steps. Thanks.

**Comment by ksaur** [comment]
Closed with #558 thank you!
