### ISSUE TITLE
tree_implementation parameter gets overwritten with onnx backend 

### ISSUE THREAD

**Issue by jfrery** [microsoft/hummingbird#564]
Hello, 

I have been trying to use the gemm with onnx backend but the onnx graph did not really look like we were using gemm tree implementation:
```python
model = convert(skl_model, backend="onnx", test_input=X, extra_config={"tree_implementation":"gemm"})
```
It seems that the `tree_implementation` parameter gets overwritten deeper in the code:

```python
        if backend == onnx.__name__:
            # vers = LooseVersion(torch.__version__)
            # allowed_min = LooseVersion("1.6.0")
            # Pytorch <= 1.6.0 has a bug with exporting GEMM into ONNX.
            # For the moment only tree_trav is enabled for pytorch <= 1.6.0
            # if vers < allowed_min:
            extra_config[constants.TREE_IMPLEMENTATION] = "tree_trav"
```
I am not sure why this is done tho? Removing this part gives me back the expected behavior.

Could you give a bit more info on what is the point of this? Can I do anything to fix this?

**Comment by ksaur** [comment]
Hi @jfrery , I think there is an open issue on this [#199](https://github.com/microsoft/hummingbird/issues/199#issuecomment-660321825).  

@interesaaat any thoughts?   It's possible that there have been upstream patches since then that could fix this, or did PR #211 already help with this?

**Comment by interesaaat** [comment]
Yes it could be that with the newest version they fixed the problem. @jfrery we had to pin the tree implementation for onnx because of a bug on onnx runtime. Can you please share your onnx + onnxruntime versions? We can try to remove the check and see if it works in our tests.

**Comment by jfrery** [comment]
Thanks for the info. Here are the versions I am using:
```python
onnx version: 1.10.2
onnxruntime version: 1.10.0
```
If I can be of any help here I would be glad to help.

**Comment by interesaaat** [comment]
Yes, we love contributions! So if you want to submit a PR which removes the pin of the tree model to `tree_trav` it would be great! 

One thing is, can you try to do an investigation on which version of pytorch breaks the conversions? You can leave your onnx dependencies as is, and try to downgrade pytorch until the conversion using gemm returns an exception. In your PR you can then uncomment the line checking the version of pytorch, and set it to the minimum version that works, while for the earlier version we can continue to force it to use `tree_trav`. Does it make sense?

**Comment by jfrery** [comment]
Yes of course I will prepare that. I think it is better to raise an exception rather than overwrite the parameter given by the user if the pytorch version is too low.

Does this sound right? I will have a PR soon.

**Comment by jfrery** [comment]
Is there a reason why this line takes in the `onnx_ml_model` rather than `model`:

https://github.com/microsoft/hummingbird/blob/2705c42585ac1d3ee69e65a93e5f59d7d42f44d5/tests/test_onnxml_decision_tree_converter.py#L37

I am not sure what we are trying to test by sending the `onnx_ml_model` here.

It seems that this test is breaking with `tree_implementation="gemm"` with the following error:
<details>
 <summary>Test error</summary>

```python
./test_onnxml_decision_tree_converter.py::TestONNXDecisionTreeConverter::test_decision_tree_regressor Failed with Error: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Transpose node. Name:'Transpose_17' Status Message: perm: [ 1 0 ] does not align with rank of input data: 1
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/dev_user/hummingbird/tests/test_onnxml_decision_tree_converter.py", line 92, in test_decision_tree_regressor
    self._test_regressor(X, model, extra_config={"tree_implementation":"tree_trav"})
  File "/home/dev_user/hummingbird/tests/test_onnxml_decision_tree_converter.py", line 66, in _test_regressor
    onnx_ml_pred, onnx_pred, output_names = self._test_decision_tree(X, model, extra_config)
  File "/home/dev_user/hummingbird/tests/test_onnxml_decision_tree_converter.py", line 54, in _test_decision_tree
    onnx_pred = onnx_model.predict(X)
  File "/home/dev_user/hummingbird/hummingbird/ml/containers/_sklearn_api_containers.py", line 119, in predict
    return self._run(self._predict, *inputs)
  File "/home/dev_user/hummingbird/hummingbird/ml/containers/_sklearn_api_containers.py", line 67, in _run
    return function(*inputs)
  File "/home/dev_user/hummingbird/hummingbird/ml/containers/sklearn/onnx_containers.py", line 216, in _predict
    return np.array(self._session.run(self._output_names, named_inputs))[0].ravel()
  File "/home/dev_user/hummingbird/env_hum/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Transpose node. Name:'Transpose_17' Status Message: perm: [ 1 0 ] does not align with rank of input data: 1
```

</details>

But the convert function is actually working fine if we send `model`  so I am a bit lost here.

**Comment by ksaur** [comment]
These tests are a little bit confusing due to sooo many different types of conversions.  (We should add more comments to our tests!)

There are two different types of conversions we can do:
1) **converting scikit-learn into onnx (vectorized with HB)**
So in this test, we would just convert `model` as you mentioned, which works as expected.  This was your original use case!

2) **converting  onnx-ml (meaning, traditional onnx) into onnx (vectorized with HB)**
To derive this onnx-ml model, we first create `model` from scikit-learn as with the first test, but then we `convert_sklearn` (a function from onnx tools, not HB) into `onnx_ml_model` on line 32 to get an onnx-ml model to test with.  We found this to be the easiest way to create these traditional onnx-ml models in a consistent way.  It seems that this is where we hit the bug with `gemm`.


But thinking about this a bit more, the code at the very beginning:
```
model = convert(SOME_MODEL_HERE, backend="onnx", test_input=X, extra_config={"tree_implementation":"gemm"})
```
should work fine if we are converting `skl -> onnx`, and only break with  `onnx-ml -> onnx`.  Maybe we can add an additional check if `SOME_MODEL_HERE` is coming from onnx-ml or not.

@interesaaat thoughts?

**Comment by interesaaat** [comment]
It looks that this error is coming from the onnxruntime. To bypass this, we can force onnxml models to not use `gemm`, and open an issue regarding this. 

You can `extra_config[constants.TREE_IMPLEMENTATION] = "tree_trav"` somewhere [in this method](https://github.com/microsoft/hummingbird/blob/2705c42585ac1d3ee69e65a93e5f59d7d42f44d5/hummingbird/ml/convert.py#L152). In this way sklearn models will use `gemm` (eventually), while onnxml models will stil use `tree_trav` until we understand where this new error is coming from.
