### ISSUE TITLE
Improper converter check

### ISSUE THREAD

**Issue by shubh0508** [microsoft/hummingbird#565]
Can someone please check this [converter check](https://github.com/microsoft/hummingbird/blob/2705c42585ac1d3ee69e65a93e5f59d7d42f44d5/hummingbird/ml/_topology.py#L205) in topology.py?
Shouldn't it be a `if converter is None:` ?

Or am I just missing something in the flow?

**Comment by ksaur** [comment]
Hi @shubh0508 Yes it definitely looks like the case!  Would you like to submit a PR fixing it? We value your contribution! :)
