### ISSUE TITLE
The sample in README seems not correct

### ISSUE THREAD

**Issue by Qianxi** [microsoft/hummingbird#573]
Hello,

I am trying to understand how Hummingbird works by sample in README, but I have a problem with the matrix C.
The second and third rows of the matrix C seems incorrect. If the input feature is [1.5, 6, 3.5, 5, 4], then input path is [1, 1, 0, 1], the product of input path and matrix C will be [2, 2, 0, 0, -2], and the output path is [1, 1, 0, 0, 0]. 

I think the matrix C should be like this:
[[1, 1, 1, -1, -1], [1, -1, -1, 0, 0], [0, 0, 0, 1, -1], [0, 1, -1, 0, 0]]
and then for the same input feature [1.5, 6, 3.5, 5, 4], the input path is still [1, 1, 0, 1], the product of input path and C will be [2, 1, -1, -1, -1]，and the output path is [1, 0, 0, 0, 0].

I wonder if there is something wrong with my understanding?

**Comment by interesaaat** [comment]
Thanks @Qianxi! You are right, good catch! We are going to contact who generate the figure and see whether they can fix it.

**Comment by vumichien** [comment]
@Qianxi Thank you very much! You are right, it's my mistake, I will change with the correct one.
