### ISSUE TITLE
output with shape [369, 1] doesn't match the broadcast shape [1, 1, 369, 1]

### ISSUE THREAD

**Issue by searope** [microsoft/hummingbird#587]
I have a sklearn's HistGradientBoostingRegressor trained on [369, 80] data to output [369, 1] result. After converting it to Hummingbird model, I'm getting this error on the very same data.

**Comment by ksaur** [comment]
Hi @searope  yes we have an issue #584 with this!

Please downgrade `"scikit-learn>=0.21.3,<1.1.0"` your scikit-learn temporarily; we plan to have a proper fix soon!

**Comment by searope** [comment]
Downgrading to scikit-learn==1.0.2 did the trick. Thank you very much.
I'm seeing 2-3 times speed improvement in prediction. Impressive!
