### ISSUE TITLE
`wheel` missing from `requirements.txt`

### ISSUE THREAD

**Issue by markusweimer** [microsoft/hummingbird#60]
I tried to run the following on a fresh VS Code Spaces instance:

```sh
$ pip install -r requirements.txt
```

And got the following errors:
```
Could not build wheels for numpy, since package 'wheel' is not installed.
Could not build wheels for scikit-learn, since package 'wheel' is not installed.
Could not build wheels for torch, since package 'wheel' is not installed.
Could not build wheels for xgboost, since package 'wheel' is not installed.
Could not build wheels for lightgbm, since package 'wheel' is not installed.
Could not build wheels for onnxconverter-common, since package 'wheel' is not installed.
Could not build wheels for scipy, since package 'wheel' is not installed.
Could not build wheels for joblib, since package 'wheel' is not installed.
Could not build wheels for future, since package 'wheel' is not installed.
Could not build wheels for protobuf, since package 'wheel' is not installed.
Could not build wheels for onnx, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for setuptools, since package 'wheel' is not installed.
Could not build wheels for typing-extensions, since package 'wheel' is not installed.
```

A quick 

```sh
$ pip install wheel
```

Fixed that. Should `wheel` be in `requirements.txt`?

**Comment by interesaaat** [comment]
Interesting. Let me try to replicate the problem and yes, I will add `wheel` to the requirements in case.

**Comment by ksaur** [comment]
I'm about confused on this; we don't take a direct dependency on wheel.  This seems more like a problem with the pip installation than Hummingbird if I'm not mistaken.

**Comment by markusweimer** [comment]
Maybe `wheel` is usually expected to be there?

**Comment by ksaur** [comment]
@markusweimer - Did you run `python -m pip install --upgrade pip` when you setup pip?

**Comment by markusweimer** [comment]
No, I did not.

**Comment by ksaur** [comment]
I haven't been able to reproduce this. Can you please explain the exact steps you tried?

**Comment by markusweimer** [comment]
I created a new Codespace [here](https://online.visualstudio.com/) and gave it the Hummingbird repo to setup from. It generated a venv with Python 3.7. That venv lacked the `wheel` installtion.

I believe this venv was created by [Oryx](https://github.com/Microsoft/Oryx). I believe that because the [documentation for codespaces](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring) says so when explaining the default of the `postCreateCommand` option:

> By default, `oryx build` is run. To disable Oryx behavior, set the value to empty string (`""`) or empty array (`[]`).

**Comment by ksaur** [comment]
The reason that I was not able to access codespaces is because the quota limit on our sub seems to be `1` codespace.  I was able to create the codespace in another sub and verify that pip update fixes the issue.
