### ISSUE TITLE
Performance Issues Using the TVM Backend

### ISSUE THREAD

**Issue by asprasad** [microsoft/hummingbird#600]
I am running inference on an XGBoost model using Hummingbird on a desktop CPU target. I've installed Pytorch, Hummingbird and TVM into a conda environment (TVM was built from source and linked to llvm-10). I have trained models serialized into XGBoost JSONs and am creating XGBoost sklearn objects from them. I am able to compile these models using Hummingbird and run them. My python code to run on PyTorch is as follows: 

xgb_model = xgb.XGBRegressor()
xgb_model.load_model(model_json)
hb_model = convert(xgb_model, 'pytorch')
// ...
pred = hb_model.predict(batch)

My python code to compile the model using the TVM backend is the following:

xgb_model = xgb.XGBRegressor()
xgb_model.load_model(model_json)
hb_model = convert(xgb_model, 'tvm', test_input=inputs[0:batch_size])
// ...
pred = hb_model.predict(batch)

Is this the right way to compile models (especially using TVM)? Do I need to enable any other TVM features (eg. auto-tuning) through the Hummingbird API? For my models, the performance of the inference with both the PyTorch and the TVM backends are roughly the same which makes me think that I may be using the TVM backend wrong. I was able to verify that the predict methods are computing the correct predictions.

**Comment by interesaaat** [comment]
Hi @asprasad, I think you are doing it right. You are measuring the performance on CPU right?

**Comment by asprasad** [comment]
Hi @interesaaat, Yes, I am running everything on a CPU.

**Comment by interesaaat** [comment]
Ok, can you share more info on the model characteristics? This is not what we usually see, TVM is in general much faster than pytorch. But maybe your model is far different than the ones we tested with.

**Comment by asprasad** [comment]
Hi @interesaaat, Thank you for your response! 

I'm using a variety of models and am seeing the same behavior for all of them (TVM not being faster than pytorch). For example, one of the models I'm testing with is trained from the airline data set using XGBoost (v 1.5). It has 13 features, 100 trees and a max depth of 9. 

Here are some other system setup details that maybe relevant. I'm using pytorch version 1.11.0, TVM version 0.9 (built from source and linked to llvm-10), Hummingbird version 0.4.4 with Python 3.9.12 (all installed using Anaconda).

Is it possible that I've not turned on some TVM optimization? Do I need to pass any parameters to the Hummingbird API to enable TVM optimizations?

**Comment by interesaaat** [comment]
I am really not sure. Hummingbird should take care of triggering the optimizations on TVM so it should be automatic from your side. Maybe PyTorch improves so much in 1.11? Or TVM has worst performance in 0.9? (we tested up to 0.8 I think) How are the performance of TVM and PyTorch compared to the original models?

**Comment by asprasad** [comment]
I haven't measured the performance of the original models. I will try installing an earlier version of TVM from conda-forge rather than building it myself and see if that resolves the problem.

**Comment by asprasad** [comment]
Hi @interesaaat, I found today that when I restrict the number of threads to 1, Torch and TVM are very similar in performance. With a higher number of threads, TVM is indeed faster than Torch as expected. I'm not sure why this is the case though. I will close this issue as it seems like the problem was that I was running single threaded.

**Comment by zhangjian94cn** [comment]
Hi @asprasad, does version 0.4.5 have supported tvm backend? When I using convert function, it just tell me 'MissingBackend'.

**Comment by asprasad** [comment]
Hi @zhangjian94cn, I built TVM locally and setup the python bindings as [documented on the TVM website](https://tvm.apache.org/docs/install/from_source.html#developers-get-source-from-github). Installing TVM (through conda) gave me the same error. Hope this helps!

**Comment by zhangjian94cn** [comment]
@asprasad  Thank you very much！

**Comment by interesaaat** [comment]
@asprasad to answer to your previous question. PyTorch doesn't do a great job in parallelizing kernels on CPU, while TVM is better.
