### ISSUE TITLE
Add support for Visual Studio Codespaces

### ISSUE THREAD

**Issue by markusweimer** [microsoft/hummingbird#61]
One way to resolve #60 is to add explicit support for dev containers to the Hummingbird repo. The documentation for that is [here](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring). Specifically, we could add a Dockerfile and settings for VS Code to use it. I am happy to give that a try if someone has a Dockerfile I can base that on.

**Comment by ksaur** [comment]
I cannot access Visual Studio Codespaces.  But here is https://github.com/microsoft/hummingbird/blob/kasaur/docker/Dockerfile

**Comment by markusweimer** [comment]
Thanks! I have fiddled around a bit and made this:

https://github.com/markusweimer/hummingbird/tree/devcontainer/.devcontainer

Is there interest to have this as a PR?

**Comment by ksaur** [comment]
Yes, that would be great, thank you!

**Comment by ksaur** [comment]
Closing via PR #71

**Comment by interesaaat** [comment]
Can we have a documentation on how to use this thing in CONTRIBUTING.md?

**Comment by ksaur** [comment]
writing now.
