### ISSUE TITLE
Add support for Lasso, Ridge and ElasticNet

### ISSUE THREAD

**Issue by fd0r** [microsoft/hummingbird#624]
There is no support for Lasso, Ridge and ElasticNet at the moment.

It should be fairly easy to add since the inference is the same as for LinearRegression.

**Comment by ksaur** [comment]
Thanks I added it to the [list](https://github.com/microsoft/hummingbird/wiki/Roadmap-for-Upcoming-Features-and-Support#other-features-requested) of requested features! I'm not sure when we'll get to this, but I labeled it as "help wanted" in the meantime!
