### ISSUE TITLE
Cannot find any way to use batching for Pytorch model

### ISSUE THREAD

**Issue by timkoval** [microsoft/hummingbird#627]
Hi!

I'm currently using your solution to convert LGBM model to Pytorch but since I got `CUDA out of memory` error I would like to use batching to solve this problem. 
I've seen  #187 but I can't find out how to use the solution that has been added. I've actually couldn't find any code related to this feature in your sources (maybe it was removed). 

I would appreciate if you can help me somehow. Thank you!

**Comment by ksaur** [comment]
Hi, What batch size are you using for inference?  Can you please provide more details about your dataset?

**Comment by timkoval** [comment]
I actually couldn't find any information about how I can use batch inference on `PyTorchSklearnContainerRegression` model. Do you have any tutorial or docs on how to make predictions by batch?

**Comment by ksaur** [comment]
By batch inference, I mean how many rows/columns are in your dataset?  In this [notebook](https://github.com/microsoft/hummingbird/blob/main/notebooks/LGBM-example.ipynb) in cell [5], we call `hb_model.predict(X)` where `X` is `X = np.random.rand(200000, 28)`.  This means that 200,000 rows with 28 columns are going into the GPU, which might cause an OOM.  You could break that 200,000 into a for-loop and feed it smaller increments at a time, but we automated this in #377 with [BatchContainer](https://github.com/microsoft/hummingbird/blob/main/hummingbird/ml/containers/batch_container.py#L17).

For an example, see our test [test_torch_regression_batch](https://github.com/microsoft/hummingbird/blob/main/tests/test_extra_conf.py#L136).  Hopefully a smaller batch size could help with your OOM!

**Comment by ksaur** [comment]
I will close this for now, please let me know if that didn't work for you and we can reopen!
