### ISSUE TITLE
Protobuf vulnerability

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#636]
From the new [microsoft/hummingbird/security/dependabot/1](https://github.com/microsoft/hummingbird/security/dependabot/1), we need to update `protobuf>=3.20.2` in `setup.py`.

However, this version doesn't work yet with onnx (See PR #635) :

```
× Encountered error while trying to install package.
╰─> onnx
```

We can try to update this later when onnx supports this

**Comment by mshr-h** [comment]
Related issue and PR
https://github.com/onnx/onnx/issues/4545
https://github.com/onnx/onnx/pull/4535
https://github.com/onnx/onnx/pull/4629

**Comment by ksaur** [comment]
All 3 of those have merged and we still have fails *sigh*, I need to investigate
