### ISSUE TITLE
Add support for scikit-learn GeneralizedLinearModels (PoissonRegressor, GammaRegressor, TweedieRegressor)

### ISSUE THREAD

**Issue by melanciani** [microsoft/hummingbird#649]
Hello ! 
It would be great if Hummingbird could support scikit-learn GLMs, and more specifically all three [PoissonRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.PoissonRegressor.html), [GammaRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.GammaRegressor.html) and [TweedieRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.TweedieRegressor.html) classes ! 

Is there currently something planned about it ?

**Comment by interesaaat** [comment]
Thanks @RomanBredehoft for the suggestion. I think these shouldn't be hard to add, I will work on it.

**Comment by melanciani** [comment]
Thanks a lot !
