### ISSUE TITLE
Varying batch sizes?

### ISSUE THREAD

**Issue by stillmatic** [microsoft/hummingbird#653]
Hi, I have some XGB/LGBM models as SKL models, and have been converting them into ONNX via Hummingbird successfully. One issue is that when converting ONNX, Hummingbird expects a test input. This test input has a batch size associated with it, but I want to pass in arbitrary batch sizes to the ONNX runtime later. Instead, the ONNX runtime insists on having the exact batch size as when Hummingbird traces it. 

Is there a good way to automatically reshape the ONNX model to accept varying/arbitrary batch sizes?

This hack appears to work, but I have not thought too carefully about it: https://github.com/stillmatic/hummingbird/commit/573c8b7dac2c8e7009727df8253b08285e06a455

**Comment by ksaur** [comment]
Hi @stillmatic!

I thought we had fixed it so that the onnx model accepted symbolic dimensions  (see [here](https://github.com/microsoft/hummingbird/blob/12e75137f631a28a59fb0ee1e21575798d436687/hummingbird/ml/_topology.py#L292)), but it's possible that onnx changed, or that your versions are different than ours.   What versions of ONNX are you using?

For example, when I run [LGBM-ONNXML-example.ipynb](https://github.com/microsoft/hummingbird/blob/main/notebooks/LGBM-ONNXML-example.ipynb) and at the end of it I do `print(onnx_model.model)`, I can see that at the end it shows the symbolic:

```
output {
    name: "probabilities"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "sym"
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
```

And if I modify the size of X:
```
X = np.array(np.random.rand(20000, 28), dtype=np.float32)
onnx_model.predict(X)
```

it still works.  Or do you mean something else?

**Comment by stillmatic** [comment]
I do see similar results, that the input and output nodes have symbolic batch results, but internal nodes (GatherElement) still expect a fixed batch size. Specifically, `Non-zero status code returned while running GatherElements node. Name:'/_operators.0/GatherElements' Status Message: GatherElements op: 'indices' shape should have values within bounds of 'data' shape. Invalid value in indices shape is: 10000`

Here is the LGBM example with a fixed test input size (20).
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/4743676/203387417-387f1f1c-16c5-49bf-998a-5190ad132275.png">

Passing without test input implies to me that Hummingbird is passing its own 10000 size input array. 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/4743676/203387535-61363d3b-e5d1-46e8-86ca-b189611c0294.png">

```
requirements:
    "onnxruntime>=1.0.0",
    "onnxmltools>=1.6.0,<=1.11.0",
    "skl2onnx>=1.7.0,<=1.12.0",
installed:
    ort 1.13.1
    onnxmltools 1.11.1
    onnx 1.12.0
    skl2onnx 1.12
```

The only mismatch I see there is that `onnxmltools` is an additional point release above the requested `11.1.0` maximum, but I doubt that is the cause of the error.

**Comment by stillmatic** [comment]
Testing your 20_000 input on this model, which expects 10_000, I am able to run it. However, this creates some very odd behavior! 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/4743676/203389268-0524f0e3-084b-438a-8590-feff71f33752.png">

First, I think the model runs only because the new batch size is larger than the original input size. Trying with a smaller batch size, eg 100, will cause the error shown in the above comment. 

Second, the result is of the original 10_000 batch size, instead of the expected 20_000 size.

**Comment by ksaur** [comment]
You're right, this appears to be a bug.
I see that we are using `sym` while in all the ONNX [tests](https://github.com/jcwchen/onnx/blob/main/onnx/test/symbolic_shape_test.py#L31) they are using `-1` so it's possible that this stopped working.   

I'll add this to the buglist!  I hope to have time to work on it within the next week or so, but in the meantime if you come up with something (in your starter PR) please do share!

**Comment by ksaur** [comment]
@stillmatic, can you open a PR with your https://github.com/stillmatic/hummingbird/commit/573c8b7dac2c8e7009727df8253b08285e06a455

**Comment by stillmatic** [comment]
Will do! I'll take a stab at updating the tests as part of that too.
