### ISSUE TITLE
pytorch problem with pip install on Python3.7 or Python3.8

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#66]
Doing pip install hummingbird-ml on Python3.7 or Python3.8 a user reported:
 
```
ERROR: Could not find a version that satisfies the requirement torch>=1.4.0 (from hummingbird-ml) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.4.0 (from hummingbird-ml)
 ```

Looks like pytorch on pypi is 1.0.2 and on the conda main channel it’s 1.3.1
Maybe linking to the installation page for pytorch would be useful.

**Comment by interesaaat** [comment]
Are you able to replicate this? I think that one possible option could be to add the pytorch url to `requirements.txt` as they are doing [here](https://stackoverflow.com/questions/57043452/how-to-add-a-package-specific-index-url-to-requirements-txt).

**Comment by ksaur** [comment]
As of today, still [pytorch on pypi is 1.0.2 ](https://pypi.org/project/pytorch/#history) but in conda [main channel ](https://anaconda.org/main/pytorch)is now at least 1.4.  I'll still pin this

**Comment by ksaur** [comment]
I'm having a surprisingly hard time reproducing this.  But, i'm going to try:
https://github.com/pytorch/pytorch/issues/29745#issuecomment-553588171

**Comment by interesaaat** [comment]
I think that this was for windows or WSL. In our CI pipeline with ubuntu all looks good.

For reference, look at my last commit [here](https://github.com/microsoft/hummingbird/pull/97)

**Comment by ksaur** [comment]
yah WSL problem. I just wanted to make sure we keep our SKL/non-pytorch friends' experience as user-friendly as possible on all platforms! :)

i think i'm going to add a link to [this](https://github.com/pytorch/pytorch/issues/29745#issuecomment-553588171) in Troubleshooting, and close this.

**Comment by ksaur** [comment]
Apparently; I already had added.   Closing.
