### ISSUE TITLE
No module named 'sklearn._loss.link'

### ISSUE THREAD

**Issue by Himanshuengg** [microsoft/hummingbird#678]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-7-1908ded060e8>](https://localhost:8080/#) in <module>
      1 import numpy as np
      2 from sklearn.ensemble import RandomForestClassifier
----> 3 from hummingbird.ml import convert
      4 
      5 # Create some random data for binary classification

3 frames
[/usr/local/lib/python3.8/dist-packages/hummingbird/ml/operator_converters/sklearn/linear.py](https://localhost:8080/#) in <module>
     11 import numpy as np
     12 from onnxconverter_common.registration import register_converter
---> 13 from sklearn._loss.link import LogLink
     14 
     15 from .._linear_implementations import LinearModel

ModuleNotFoundError: No module named 'sklearn._loss.link'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

**Comment by mshr-h** [comment]
Which sklearn version do you use?
You need at least 1.1.0 or above.

**Comment by Himanshuengg** [comment]
Thanks for the information. After updating sklearn version my issue has been resolved.
