### ISSUE TITLE
LLVM macos pipeline error

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#680]
Pipeline cache expired, triggering a TVM rebuild.

While installing TVM in [pipeline](https://github.com/microsoft/hummingbird/actions/runs/4009447455/jobs/7046411881):

```
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Use llvm-config=/usr/local/opt/llvm@14/bin/llvm-config --link-static
CMake Error at cmake/utils/FindLLVM.cmake:76 (message):
  Fatal error executing: /usr/local/opt/llvm@14/bin/llvm-config --link-static
  --libfiles
Call Stack (most recent call first):
  cmake/modules/LLVM.cmake:[31](https://github.com/microsoft/hummingbird/actions/runs/4009447455/jobs/7046411881#step:16:32) (find_llvm)
-- Configuring incomplete, errors occurred!
  CMakeLists.txt:475 (include)
See also "/Users/runner/work/hummingbird/tvm/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ksaur** [comment]
CC: @mshr-h  - Is this something you have seen before?
I was looking for the last successful rebuild of this in the Action history, but I think it expired

**Comment by mshr-h** [comment]
I haven't seen any similar error. I'll take a look at it.

**Comment by mshr-h** [comment]
The macOS 12 image has LLVM 15 by default. When building TVM with LLVM@15, we got zstd link error.
By installing LLVM@14 and using it, the problem was solved.

**Comment by ksaur** [comment]
> The macOS 12 image has LLVM 15 by default. When building TVM with LLVM@15, we got zstd link error.
By installing LLVM@14 and using it, the problem was solved.

Interesting.  Thanks so much for the investigation and temp fix!
