### ISSUE TITLE
[RFC] Periodically run CI pipeline

### ISSUE THREAD

**Issue by mshr-h** [microsoft/hummingbird#683]
... to be able to catch dependent package updates sooner.

Sometimes the CI pipeline breaks due to dependent package updates. #592 #667
This is especially a problem for new contributors.

By running GH Actions build workflow periodically(such as daily/weekly), we can catch those breakages sooner.

The downside is notifications will be annoying.

What do you think? @ksaur @interesaaat

**Comment by ksaur** [comment]
Absolutely, good idea.  This is something we talked about in the past, but I think we should actually do it now. :-D

We find that lots of new releases happen on Fridays, and I usually have some time Friday afternoons (PST) to fix things, so maybe we could setup a Friday mid-day run.  I think we just need to add [this](https://github.com/marketplace/actions/schedule-job-action)? Any objections Matteo?

**Comment by interesaaat** [comment]
No objection, this is a really good idea. Even better if we could add some sort of condition, like run on Friday afternoon if we have no previous run this week (or something along this line).

**Comment by ksaur** [comment]
I can work on implementing this on Friday, or if someone else wants to start, that is fine as well! :)

**Comment by mshr-h** [comment]
> I think we just need to add [this](https://github.com/marketplace/actions/schedule-job-action)?

Or we can use a schedule trigger event.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by mshr-h** [comment]
We can retrieve the start time of the last workflow by the command below.
```
$ curl https://api.github.com/repos/microsoft/hummingbird/actions/workflows/pythonapp.yml/runs 2>/dev/null | jq -r '.workflow_runs[0].run_started_at'
2023-02-06T18:40:27Z
```

Or maybe we can use this.
https://github.com/actions/github-script
