### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by tgaddair** [microsoft/hummingbird#688]
Hi, it looks like there have been several notable improvements since November, including https://github.com/microsoft/hummingbird/pull/674, which we need to unblock our use of Hummingbird in [Ludwig](https://github.com/ludwig-ai/ludwig). We're currently requiring users to install Hummingbird from GitHub directly, but this is not compatible with PyPI.

Can you create a new patch release with this change included, or a new minor release with the latest changes? Thanks.

**Comment by ksaur** [comment]
Hi @tgaddair, yes we were waiting on #675 but that is 2 weeks past!

New release will be out by the end of the week at the latest. Thanks!

**Comment by tgaddair** [comment]
Awesome, thank you!

**Comment by ksaur** [comment]
Closing with https://pypi.org/project/hummingbird-ml/0.4.8/#history !

**Comment by tgaddair** [comment]
Thanks for the quick turnaround on this! Much appreciated.
