### ISSUE TITLE
TVM MacOS pipeline intermittent failures

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#715]
Recently we've been seeing failures like [this](https://github.com/microsoft/hummingbird/actions/runs/5316237754/jobs/9625542616?pr=713#step:19:3730) and [this](https://github.com/microsoft/hummingbird/actions/runs/5295167134/jobs/9585215143#step:19:3734):

```
Processing ./dist/tvm-0.10.0-cp38-cp38-macosx_11_0_x86_64.whl
ERROR: Cannot install tvm 0.10.0 (from /Users/runner/work/hummingbird/tvm/python/dist/tvm-0.10.0-cp38-cp38-macosx_10_15_x86_64.whl) and tvm 0.10.0 (from /Users/runner/work/hummingbird/tvm/python/dist/tvm-0.10.0-cp38-cp38-macosx_11_0_x86_64.whl) because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

The conflict is caused by:
    The user requested tvm 0.10.0 (from /Users/runner/work/hummingbird/tvm/python/dist/tvm-0.10.0-cp38-cp38-macosx_10_15_x86_64.whl)
    The user requested tvm 0.10.0 (from /Users/runner/work/hummingbird/tvm/python/dist/tvm-0.10.0-cp38-cp38-macosx_11_0_x86_64.whl)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

This seems to happen every other time, todo: investigate. 
cc: @mshr-h , have you seen this other places?

**Comment by mshr-h** [comment]
No, I haven't seen any similar message.

**Comment by mshr-h** [comment]
@ksaur 
Can you try to remove the GHA cache and run the pipeline again?

I ran again the pipeline and found that there are multiple whl package in python/dist.
The 10_15 whl was created in the previous pipeline execution and restored from the cache.
Recent pipeline executions create 11_0 whl, then try to install them at the same time which caused the dependency conflict.

> -rw-r--r--  1 runner  staff  42055067 Feb 24 22:03 tvm-0.10.0-cp38-cp38-macosx_10_15_x86_64.whl
-rw-r--r--  1 runner  staff  42055470 Jun 20 02:39 tvm-0.10.0-cp38-cp38-macosx_11_0_x86_64.whl

**Comment by ksaur** [comment]
Done! Crossing fingers!
