### ISSUE TITLE
Make the dev container more comfy

### ISSUE THREAD

**Issue by markusweimer** [microsoft/hummingbird#72]
The current dev container is derived off of a super barebones image. Not even `less` is installed. I will be looking into finding a more comfy base image, probably starting with the ones found [here](https://github.com/microsoft/vscode-dev-containers).

**Comment by markusweimer** [comment]
I have something working [here](https://github.com/markusweimer/hummingbird/tree/mweimer/72). It uses a devcontainer base image with better tools installed, and also configures VSCode to use `bash` instead of `sh`.

There are very many additional niceties that could be done to the user setup (better prompt and such). However, I think that is better left to the per-user dotfiles repo.

This container is still using Python 3.6, while the one for jupyter uses Python 3.7. Which version does Hummingbird actually require? I took 3.6 from `setup.py`.

**Comment by markusweimer** [comment]
@interesaaat, can you help with this?

> This container is still using Python 3.6, while the one for jupyter uses Python 3.7. Which version does Hummingbird actually require? I took 3.6 from `setup.py`.

**Comment by interesaaat** [comment]
Sorry I forgot about replying here. I think 3.6 is safer but we support python 3 in general.

**Comment by markusweimer** [comment]
Thanks, I will send the change as a PR then

**Comment by ksaur** [comment]
closing re: #75
