### ISSUE TITLE
Example cases for DecisionTreeClassifier

### ISSUE THREAD

**Issue by umairjavaid** [microsoft/hummingbird#735]
Can you please share some test cases where you have achieved speed up in DecisionTreeClassifier

**Comment by interesaaat** [comment]
Hi! I suggest you to check our paper. And you can try yourself: we have the benchmarking code used in the paper [here](https://github.com/microsoft/hummingbird/tree/main/benchmarks/trees).

**Comment by umairjavaid** [comment]
Thank you
