### ISSUE TITLE
Is "Hummingbird" trademarked?

### ISSUE THREAD

**Issue by mshr-h** [microsoft/hummingbird#768]
I'm just curious if the project name 'Hummingbird' is trademarked.
If so, it may be helpful to add that to README.
@ksaur @interesaaat

**Comment by interesaaat** [comment]
I don’t think it is trademarked but maybe Karla knows better.

**Comment by ksaur** [comment]
No, this is not trademarked

**Comment by mshr-h** [comment]
Ok, thanks!
