### ISSUE TITLE
backorder message after product into cart

### ISSUE THREAD

**Issue by hogo20** [microsoft/hummingbird#778]
hello
in hummingdird 0.2, when product add to cart in out of stock,  then message shows.
I think like with classic, when we increase the quantity, the increase message should be displayed over stock, not after adding to cart.
![Uploading dddd.png…]()

**Comment by ksaur** [comment]
Hi, I think you have the wrong repo. We do not have anything related to carts or backorders, this is a library for compiling trained traditional ML models into tensor computations. Please see our readme, and find a different Hummingbird! :)
