### ISSUE TITLE
Merge DecisionTree and GBDT implementations into one

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#80]

**Comment by ksaur** [comment]
I think we discussed this before, but I thought we decided against it.   I'm curious what made you want to revisit?

**Comment by interesaaat** [comment]
Did we? I was not even aware we could merge them until 1 week ago.

**Comment by interesaaat** [comment]
Ah I think you are referring to the convert files. No those will be separate. Here I mean the pytorch implementation.

**Comment by ksaur** [comment]
Ah, i see. Ok makes sense!

**Comment by interesaaat** [comment]
I tried with #222 but apparently we will have to live with 2 different implementations for the moment. The DecisionTree\RandomForest one has each tree storing the different class probabilities, while the GBDT implementations have a tree per class.
