### ISSUE TITLE
Notebooks don't work as-is

### ISSUE THREAD

**Issue by sergeyf** [microsoft/hummingbird#82]
For example, the lightgbm example notebook has:

`from hummingbird.ml import convert`

and then

`hb_model = convert(model, 'pytorch')`

This returns an error:
```
In [14]: hb_model = convert(model, 'pytorch')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-5658f007aeed> in <module>
----> 1 hb_model = convert(model, 'pytorch')

TypeError: 'module' object is not callable
```

Should it instead be: 
` from hummingbird.ml.convert import convert_lightgbm as convert`?

**Comment by interesaaat** [comment]
We recently changed the API and apparently not all notebooks got properly updated (my fault). I will send a PR shortly. Thanks for finding this!

**Comment by sergeyf** [comment]
My pleasure!

**Comment by interesaaat** [comment]
@sergeyf did you `pip install hummigbird-ml` or installed it directly from master. I believe you are `pip install`ing and the version of pip is not update with the latest API changes. To check this, you could try to run the following: instead of `hb_model = convert(model, 'pytorch')` use `hb_model = model.to('pytorch')`.

**Comment by sergeyf** [comment]
Yes, I did pip install. Makes sense that it's out of date - I'll close this issue.

Thanks.

**Comment by jspisak** [comment]
Hey Folks - i still see the NBs failing after pip installing HummingBird. Is there an ETA to update PyPI?

**Comment by interesaaat** [comment]
We are waiting to merge the hist gbdt and we will push a new version. Our plan is to have a release approximately every month.

**Comment by ksaur** [comment]
pushed https://pypi.org/project/hummingbird-ml/0.0.2/
