### ISSUE TITLE
Add badge for code coverage in README.md

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#9]

**Comment by ksaur** [comment]
fixed by [commit](https://github.com/microsoft/hummingbird/commit/2c95f488a4dc31cae0915faf958efb4d848af9f3) for now, more elaborate solution to come.

**Comment by ksaur** [comment]
Notes:  github actions can regenerate a badge for you ,but the badge has to go SOMEWHERE.  So for now, I'm generating the .svg badge as a commit hook and uploading it as part of a commit.

**Comment by ksaur** [comment]
This solution doesn't work well.  Let's wait to make this repo public and figure out a fancier external solution
