### ISSUE TITLE
Add sklearn's DecisionTreeRegressor

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#98]

**Comment by KranthiGV** [comment]
Hi team, I would love to take this up, if no one already did.
Apart from the changes to supported operators, operator list, etc. I would have to implement `convert_sklearn_decision_tree_regressor` similar to `convert_sklearn_decision_tree_classifier`.
I believe I may be able to leverage the random forests regressor converter similar to how decision tree classifier did. I will have to see how that works out.

**Comment by interesaaat** [comment]
Go for it! You are right, you can look at `tree_classifier` and `random_forest_regressor` on how to make it work.

**Comment by interesaaat** [comment]
Closed in #102.
